### ISSUE TITLE
Pretrained Model and Source Code

### ISSUE THREAD

**Issue by XuankeShi** [nv-tlabs/GET3D#1]
Waiting.......

**Comment by subhankar-trisetra** [comment]
> Waiting.......

+1

**Comment by MMUmedaGIT** [comment]
anxiously!

**Comment by SteveJunGao** [comment]
We're in the final stage of code review, we will release by the end of this week (likely Friday).

Unfortunately, we won't be able to release the pretrained weights, but we will provide all the details for training the model.

**Comment by Lhun** [comment]
@SteveJunGao did I read this right? It was only trained for a week to get your pretrained weights which had the results in the video? 🤯
I'm really excited to see people take the code and run with it, I imagine datasets like ObjectNet3D and many others could be used here, and then for the textures and images, Stable Diffusion?
I think for scene generation this is really exciting, Ikea and HomeDepot and Quixel have huge datasets...

**Comment by MMUmedaGIT** [comment]
> 

Can it be trained on just 8 GB of VRAM?

**Comment by SteveJunGao** [comment]
It only needs 2-3 days to train the model to get the results in the videos. But we were training on 8 V100 GPUs, and each GPU needs 16GB memory (or 32 GB memory depending on the model you choose). If training on 8 A100 GPUs, it can be ~2.5x faster.

It might be possible to train with 8GB GPU memory if reducing the network size, rendering lower image resolution, etc. We haven't tested this yet, but would be great to see the results!

Please stay tuned! We're releasing it soon, and we can talk more about it with the code!

**Comment by XuankeShi** [comment]
I think if you can release the pre-trained model to a certain extent, it will be of great benefit to the promotion of your work.  Maybe not the best of your models, I think 

> We're in the final stage of code review, we will release by the end of this week (likely Friday).
> 
> Unfortunately, we won't be able to release the pretrained weights, but we will provide all the details for training the model.

I think if you can release the pre-trained model to a certain extent, it will be of great benefit to the publicity and promotion of your work. The best model may not be needed, but providing a pre-trained model can provide relevant scholars with great benefits Convenience to better promote the advancement of computer vision 3D understanding. At the same time, I also wish that your work can be noticed by more people

**Comment by XuankeShi** [comment]
I think if you can release the pre-trained model to a certain extent, it will be of great benefit to the publicity and promotion of your work. The best model may not be needed, but providing a pre-trained model can provide relevant scholars with great benefits Convenience to better promote the advancement of computer vision 3D understanding. At the same time, I also wish that your work can be noticed by more people

**Comment by XuankeShi** [comment]
> It only needs 1 week to train the model to get the results in the videos. But we were training on 8 V100 GPUs, and each GPU needs 16GB memory (or 32 GB memory depending on the model you choose). If training on 8 A100 GPUs, it can be ~2.5x faster.
> 
> It might be possible to train with 8GB GPU memory if reducing the network size, rendering lower image resolution, etc. We haven't tested this yet, but would be great to see the results!
> 
> Please stay tuned! We're releasing it soon, and we can talk more about it with the code!

**Comment by XuankeShi** [comment]
> It only needs 1 week to train the model to get the results in the videos. But we were training on 8 V100 GPUs, and each GPU needs 16GB memory (or 32 GB memory depending on the model you choose). If training on 8 A100 GPUs, it can be ~2.5x faster.
> 
> It might be possible to train with 8GB GPU memory if reducing the network size, rendering lower image resolution, etc. We haven't tested this yet, but would be great to see the results!
> 
> Please stay tuned! We're releasing it soon, and we can talk more about it with the code!

**Comment by XuankeShi** [comment]
> We're in the final stage of code review, we will release by the end of this week (likely Friday).
> 
> Unfortunately, we won't be able to release the pretrained weights, but we will provide all the details for training the model.

I think if you can release the pre-trained model to a certain extent, it will be of great benefit to the publicity and promotion of your work. It can provide great convenience for relevant researchers by providing a pre-trained model. Essentially, we both hope to promote the advancement of computer vision 3D understanding. At the same time, I also wish that your work can be noticed by more people.

**Comment by SteveJunGao** [comment]
Unfortunately, we are not able to release the pretrained models, due to licensing restrictions of the data.

**Comment by SteveJunGao** [comment]
Source code is uploaded!

**Comment by zhanghongyong123456** [comment]
> Source code is uploaded!

Thank you

**Comment by SteveJunGao** [comment]
As a small update, We have released the pretrained models[here](https://github.com/nv-tlabs/GET3D/tree/master/pretrained_model)
