### ISSUE TITLE
Not Found Camera Root

### ISSUE THREAD

**Issue by AmanKishore** [nv-tlabs/GET3D#10]
When training with the following command:
```
python train_3d.py --outdir=results/ --data=render_shapenet_data/dataset/img/02958343/ --camera_path=render_shapenet_data/dataset/camera/02958343/ --gpus=8 --batch=32 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0
```
I keep getting this output:
```
20%|##        | 57/279 [00:51<02:59,  1.24it/s]==> not found camera root
==> not found camera root
==> not found camera root
```

Do I need to fix something?

**Comment by SteveJunGao** [comment]
Hi, Thanks for trying out our code!!!!

In your command, you need to set the `camera_path` to be `--camera_path=render_shapenet_data/dataset/camera` ;)

**Comment by AmanKishore** [comment]
Thank you! FYI I had to add `--shm-size=20gb` to the docker run command

**Comment by SteveJunGao** [comment]
Thanks! It's good to know this!
