### ISSUE TITLE
Trainning Iteration Problem

### ISSUE THREAD

**Issue by r530044129** [nv-tlabs/GET3D#100]
Hi, I found GET3D really need a lot time to trainning.
I just try to trainning it with --kimg 100 or --kimg 200 with 6k png, but the result were poor. 
![fakes_000071_00](https://user-images.githubusercontent.com/22882223/221074569-68ba945b-aee2-4ee7-98d6-706ae8a213fa.png)
![reals](https://user-images.githubusercontent.com/22882223/221074589-2bdf44ca-6396-458d-82e2-b1066f9df474.png)
this is a comparison of kimg-70 and real one.

Q1: I just want to know, generally, how much kimg is suitable to get the rough shape?
Q2: By default, the blender render some 1024*1024 png, if I use Blender to render 512*512 png to trainning, will the trainning speed be faster?

Thanks

**Comment by SteveJunGao** [comment]
Hi @r530044129,

Re Q1: Typically, you can get the rough shape at around 1000 kimg, and it can become better as you train it longer. I typically train with 4000-8000 kimg 

Re Q2: Yes, the training can be much faster if you train with 512x512, you can achieve this by setting the flag `--img_res=512`

**Comment by r530044129** [comment]
Get it, thanks.
Q3: Any reason why juse random sample the up-hemisphere views in Blender? Can I juse change the code to random sample the whole sphere around the object, if I want more down-side details. Does that theoretically affect the algorithm result?

**Comment by Bathsheba** [comment]
You can change this by editing data_camera_mode's in sample_camera_distribution.py. 
For training on your own data it is recommended to create your own data_camera_mode, I did this and made it whole sphere as you describe. I haven't finished training but it seems to be working.

**Comment by samrat213** [comment]
@Bathsheba i am also trying to train on my own dataset. can you please tell me how to create data_camera_mode?

**Comment by r530044129** [comment]
> @Bathsheba i am also trying to train on my own dataset. can you please tell me how to create data_camera_mode?

you can just use the '--use_shapenet_split 0', and use old data mode, such as '--data_camera_mode shapenet_motorbike'.
because you have set not use any split data in training, so the data camera mode is useless, you can set it to any exist mode.

It's work for me

**Comment by Bathsheba** [comment]
I did not use a split, but I think if you want the full benefit of the camera condition, and you have your own set of camera angles, then you do need a data_camera_mode. 

I changed the scripts in render_shapenet_data to give a wider range of angles (plus 6 axial views) for my data, and then in  sample_camera_distribution.py I added a new data_camera_mode with matching range. That's all. :-)

**Comment by SteveJunGao** [comment]
Thanks @Bathsheba for suggesting the solution!

Yes, you can change the blender script to sample the whole sphere to render the shapes and also change the `sample_camera_distribution.py` scripts accordingly to same the cameras for the generator (it also need to be full sphere).

**Comment by YiX98** [comment]
Hello @r530044129 ! May I ask how many 3d objects you have to render that 6k PNGs? I wonder whether there will be an overfitting if I only got less than 100 objects and render to near 10k PNGs with kimg equals 6000.

**Comment by r530044129** [comment]
@YiX98 Maybe 400~500 objs. As my experience, 100 obj is not enought in most time.

**Comment by SteveJunGao** [comment]
In my case, I tried on ShapeNet Motorbike category which has about 200-300 objs, and it can work decently, but I haven't tried less than 100 objs.
