### ISSUE TITLE
Is there a way to get ground truth sdf value from the deftet representation from a ground truth mesh

### ISSUE THREAD

**Issue by iszihan** [nv-tlabs/GET3D#102]
Hello, I'm wondering if one has a ground truth 3D mesh, if there is a way to get the ground truth sdf value at the deformed tet vertices from this ground truth mesh?

**Comment by hitsz-zuoqi** [comment]
> Hello, I'm wondering if one has a ground truth 3D mesh, if there is a way to get the ground truth sdf value at the deformed tet vertices from this ground truth mesh?

You should refer to DMTet, and use an optimization-based paradigm to get the "fake ground truth" of SDF values. There is a paper that does a similar job called TetGAN. But the performance is not very good as I see.

**Comment by SteveJunGao** [comment]
Hi @iszihan ,

You can try to use [Nvdiffrec](https://github.com/NVlabs/nvdiffrec) to optimize a tet grid with SDF values if you have a ground truth mesh.

If the ground truth mesh is watertight, then directly computing the SDF values for each vertex would also work (it won't get the  deformation, so the shape would be bumpy)

**Comment by SteveJunGao** [comment]
Close the issue as no response for three weeks, feel free to reopen it if any issue is raised!
