### ISSUE TITLE
train on data with mask unavailable

### ISSUE THREAD

**Issue by samrat213** [nv-tlabs/GET3D#104]
i have RGB images instead of RGBA images.
is there any hyperparameters that enables training on RGB or I have to change __getitem__() in dataset.py.
it seems there is option of mask not available but it is not working properly

**Comment by SteveJunGao** [comment]
Hi @samrat213 ,

Currently GET3D can not be trained on the data without masks, if you have RGB images, I suggest you to run segmentation models to get the masks for them

**Comment by SteveJunGao** [comment]
Close the issue as no response for three weeks, feel free to reopen it if any issue is raised!
