### ISSUE TITLE
how to train with my own data?

### ISSUE THREAD

**Issue by icoz69** [nv-tlabs/GET3D#105]
hi, I have trained EG3D successfully with my own data that are synthesized from meshes. Can the data be directly used to train GET3D?

**Comment by samrat213** [comment]
possibly yes
you would need image with mask. it seems EG3D doesn't need mask.
then change the dataset file to get the image list. 
I am also trying to train on wild shoe dataset

**Comment by icoz69** [comment]
> possibly yes you would need image with mask. it seems EG3D doesn't need mask. then change the dataset file to get the image list. I am also trying to train on wild shoe dataset

hi, thanks for your reply. I saw there is --camera_path PATH_TO_RENDER_CAMERA for training. How generate it from my own data?

**Comment by Maro1** [comment]
> > possibly yes you would need image with mask. it seems EG3D doesn't need mask. then change the dataset file to get the image list. I am also trying to train on wild shoe dataset
> 
> hi, thanks for your reply. I saw there is --camera_path PATH_TO_RENDER_CAMERA for training. How generate it from my own data?

You can have a look at [render_shapenet.py](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py) to see how it's generated when rendering ShapeNet, from line 233.` You need to give the elevation and rotation in degrees of the camera for each frame.

**Comment by SteveJunGao** [comment]
Close the issue as no response for one month, feel free to reopen if any issue raised !
