### ISSUE TITLE
About Computer Performance

### ISSUE THREAD

**Issue by 332590225** [nv-tlabs/GET3D#106]
Sorry to bother you with this kind of question

I'm a Chinese indie game programmer and I want to use this AI to train to model my own game.

But my computer is low performance 
CPU is R5 5600H 
GPU is RTX 4080 16G RAM

Can I use such a computer for training AI? Will the training speed be extremely slow due to lack of performance?

**Comment by SteveJunGao** [comment]
Hi @332590225 

I think RTX 4080 would be fine to train such model, you might need to use a smaller model size. 

You can do this by changing the parameters: 
`--img_res=512`

**Comment by SteveJunGao** [comment]
Close the issue as no response for three weeks, feel free to reopen if any issue raised
