### ISSUE TITLE
Setting up pytorch plugin: ”upfirdn2d_plugin“ ... failed

### ISSUE THREAD

**Issue by YiX98** [nv-tlabs/GET3D#108]
My nvidia-smi outputs the driver version: 470.141.03 and CUDA version: 11.4 on Quadro RTX 6000
My nvcc -V outputs "11.1", same as `torch.version.cuda` outputs in python3.8
I got an Error of:
`Import Error:  ~/.cache/torch_extensions/upfirdn2d_plugin/......-quadro-rtx-6000/upfirdn2d_plugin.so: cannot open shared object file: no such file or directory`
I tried deleted the directory "torch_extensions" but didn't work.

**Comment by SteveJunGao** [comment]
It seems like this bug is related you failed to compile the package `upfirdn2d_plugin`, do you see any other error message when you run the code?

**Comment by YiX98** [comment]
> It seems like this bug is related you failed to compile the package `upfirdn2d_plugin`, do you see any other error message when you run the code?

Thank you for your reply!
Yes it is a compilation fail, so I manually get into the folders of plugins in torch_extensions, and I run `ninja` in the directory then the problem solved. I also wonder how can I run GET3D code in a new environment without manually ninja compilation.

Besides, I tried the 2d inference of shapenet_car with pretrained chekpoint used, may I ask why in each inference I get the same images? Since I would like to get diverse car generations.

**Comment by YiX98** [comment]
> It seems like this bug is related you failed to compile the package `upfirdn2d_plugin`, do you see any other error message when you run the code?

Thank you for your reply!
Yes it is a compilation fail, so I manually get into the folders of plugins in torch_extensions, and I run `ninja` in the directory then the problem solved. I also wonder how can I run GET3D code in a new environment without manually ninja compilation.

Besides, I tried the 2d inference of shapenet_car with pretrained chekpoint used, may I ask why in each inference I get the same images? Since I would like to get diverse car generations.

**Comment by Bathsheba** [comment]
Re same cars, try a different --seed ?

**Comment by YiX98** [comment]
> Re same cars, try a different --seed ?

@Bathsheba Thank you!
Also, do you know why I got another error when I render the shapeNet
`File "/GET3D/render_shapenet_data/render_shpaenet.py", line 196, in <module>
        light2 = bpy.data.lights['Area']
KeyError: 'bpy_prop_collection[key]: key "Area" not found' `

**Comment by YiX98** [comment]
> > Re same cars, try a different --seed ?
> 
> @Bathsheba Thank you! Also, do you know why I got another error when I render the shapeNet `File "/GET3D/render_shapenet_data/render_shapenet.py", line 196, in <module> light2 = bpy.data.lights['Area'] KeyError: 'bpy_prop_collection[key]: key "Area" not found' `

@Bathsheba I have solved this peoblem but thank you again!
It is because I change the language of blender in the GUI, after I change it back to English it ran properly

**Comment by YiX98** [comment]
> > It seems like this bug is related you failed to compile the package `upfirdn2d_plugin`, do you see any other error message when you run the code?
> 
> Thank you for your reply! Yes it is a compilation fail, so I manually get into the folders of plugins in torch_extensions, and I run `ninja` in the directory then the problem solved. I also wonder how can I run GET3D code in a new environment without manually ninja compilation.

@SteveJunGao Sorry for the delay of Error message as I have to download them from a offline remote env.
`Creating output directory...
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
Traceback (most recent call last):
  File "train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/xuyi/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xuyi/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xuyi/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xuyi/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "/mnt/MountVolume2/xuyi/code/GET3D/training/training_loop_3d.py", line 113, in training_loop
    upfirdn2d._init()
  File "/mnt/MountVolume2/xuyi/code/GET3D/torch_utils/ops/upfirdn2d.py", line 28, in _init
    _plugin = custom_ops.get_plugin(
  File "/mnt/MountVolume2/xuyi/code/GET3D/torch_utils/custom_ops.py", line 140, in get_plugin
    torch.utils.cpp_extension.load(
  File "/home/xuyi/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/home/xuyi/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/xuyi/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/xuyi/.cache/torch_extensions/upfirdn2d_plugin/7299e3f0b4b270a9768af03373336fdf-quadro-rtx-6000/upfirdn2d_plugin.so: cannot open shared object file: No such file or directory`

**Comment by cxqdderbth742** [comment]
Hello YiX98! How did you solve the problem by using ninja to compile the plugin. Could you provide the powershell command? Thanks :>

**Comment by cxqdderbth742** [comment]
when I run ninja in C:\Users\username\AppData\Local\torch_extensions\torch_extensions\Cache\upfirdn2d_plugin\ folder I get 'ninja : no work to do'

**Comment by YiX98** [comment]
@cxqdderbth742 I recommend you uninstall the ninja and follow the instructions here [](https://github.com/ninja-build/ninja) to reinstall ninja and bootstrap, remember to ensure you have  the re2c installed before and no error occurs except warnings. These steps prevented me from manually compile plugins. Also you may interested in, I had an error of can’t find `Python.h` and solved by `sudo apt-get install python3.8-dev`

**Comment by YiX98** [comment]
> @cxqdderbth742 I recommend you uninstall the ninja and follow the instructions here [ninja-build](https://github.com/ninja-build/ninja) to reinstall ninja and bootstrap, remember to ensure you have the re2c installed before and no error occurs except warnings. These steps prevented me from manually compile plugins. Also you may interested in, I had an error of can’t find `Python.h` and solved by `sudo apt-get install python3.8-dev`

I close this issue as problem solved by as quoted or manually compile using ninja.
