### ISSUE TITLE
Cannot retrieve the public link

### ISSUE THREAD

**Issue by RichardHusar** [nv-tlabs/GET3D#109]
![image](https://user-images.githubusercontent.com/76170638/225622639-a0724cb6-6b81-4572-95d6-1af46a26ca71.png)
hello I have this problem here I cant manually upload a file coz its too big and google colab will disconnect before its uploaded every time I try

**Comment by SteveJunGao** [comment]
Hi @RichardHusar ,

I haven't seen this error before. The link I shared is already a public link and Anyone with the link should have permission.

How quickly it would be to upload one file (not all the four checkpoints)?

**Comment by SteveJunGao** [comment]
That's a werid bug...., maybe you can try to run the notebook locally and see if the problem still exists?

**Comment by SteveJunGao** [comment]
Closing this issue as haven't heard back for three months, please feel free to reopen it if you still find the problem!
