### ISSUE TITLE
Why model inference can generate chassis of car?

### ISSUE THREAD

**Issue by YiX98** [nv-tlabs/GET3D#110]
Since the training data of shapenet_car is rendered from upper hemisphere. Why in the inference using pre-trained checkpoint we can get the geometry of the down side of cars?

**Comment by SteveJunGao** [comment]
Hi @YiX98 ,

That's a good point! Yes, we only rendered the upper hemisphere, but it can definitely be changed to the whole sphere (and you also need to modify the camera distribution when you sample the camera during training), and it should also work.

the pre-trained checkpoint can only make the down side of the cars a plane (there are no any geometric details of the down side of the car), the reason why we can get this outcome is that the side view can help to carve out the bottom of the shape, thus helps us to get the plane on the bottom.

**Comment by SteveJunGao** [comment]
Closing this issue as haven't heard back for three months, please feel free to reopen it if you still find the problem!
