### ISSUE TITLE
[F glutil.cpp:338] eglInitialize() failed

### ISSUE THREAD

**Issue by tcabezon** [nv-tlabs/GET3D#115]
I get this comment when I try to run inference on the model.  I even get the error when I run the 'GET3D-pretrain-inference.ipynb' google colab that is provided as example.

[F glutil.cpp:338] eglInitialize() failed

**Comment by tcabezon** [comment]
<img width="1456" alt="Screen Shot 2023-04-05 at 18 55 52" src="https://user-images.githubusercontent.com/91072577/230229875-66623f1b-6fee-4167-8899-eba57a8b8e9a.png">

**Comment by buptzh111** [comment]
Hi @tcabezon , I've met the same problem, and I solved it by replacing "dr.RasterizeGLContext" with "dr.RasterizeCudaContext" when doing inference. You can find it in training/networks_get3d.py, line 385, and uni_rep/render/neural_render.py, line 59.

**Comment by SteveJunGao** [comment]
Thank you @buptzh111 for providing the fix!

Yes, changing from GL to Cuda in Nvdiffrast would fix the problem

**Comment by Walterkd** [comment]
> 

Works for me too!

**Comment by Remember12344** [comment]
> Thank you @buptzh111 for providing the fix!
> 
> Yes, changing from GL to Cuda in Nvdiffrast would fix the problem



> Thank you @buptzh111 for providing the fix!
> 
> Yes, changing from GL to Cuda in Nvdiffrast would fix the problem

does it mean i need to change all the GL to cuda in Nvdiffrast file?
