### ISSUE TITLE
About world coordinate

### ISSUE THREAD

**Issue by ChencongZJU** [nv-tlabs/GET3D#116]
Hi, thanks for your great work.
I'm trying to use get3d to generate vehicle models for vehicle in real data scenario. 
My problem is about world coordinate. Is the center of the world coordinate system at the center of the car? And what direction does its x-y-z axis point to？

**Comment by SteveJunGao** [comment]
Hi @ChencongZJU ,

Thanks for your interest in our work!

You can run the inference on our pretrained checkpoint and visualize the 3D shape in meshlab to see what each direction would point to :) 

To answer your question, yes, the center of the world coordinate system is at the center of the car (0,0,0), and the x-axis is the frontal of the car, y-axis is the top of the car, z-axis is the side of the car.
