### ISSUE TITLE
Render generated shapes with shadow

### ISSUE THREAD

**Issue by bbzhu-jy16** [nv-tlabs/GET3D#118]
Hi, thanks for your great work. I want to know how to render the mesh with shadow. (e.g., Fig.1 in your paper)
Could you please provide the code or method to render files in *.obj format to get those results.

**Comment by SteveJunGao** [comment]
Hi @bbzhu-jy16 , 

render the generated shapes with shadow is done in Blender, and we haven't shared the code in this script. 

You may find this [package](https://github.com/HTDerekLiu/BlenderToolbox) useful for you to render the shapes with shadow, I borrowed the code from that package to render the figure 1

**Comment by SteveJunGao** [comment]
Closing this issue as haven't heard back for two months, please feel free to reopen it if you still find the problem!
