### ISSUE TITLE
Support for ShapeNet V2

### ISSUE THREAD

**Issue by lalalune** [nv-tlabs/GET3D#12]
Question--

1. is there any reason, other than normalizing folder structure, that ShapeNetCore V2 wouldn't work, or reason you chose ShapeNet V1 for the release?
2.  Would you accept a PR for support for ShapeNet V2?

**Comment by SteveJunGao** [comment]
Hi @lalalune 

Re 1: Technically speaking, ShapeNetCore v2 should also work, we didn't have specific requirements on the dataset. We choose to release the support for ShapeNetCore v1 as our paper is mainly experimenting with it. 

Re 2: Yes, we're happy to accept a PR for it

**Comment by lalalune** [comment]
I have added details in this pr: https://github.com/nv-tlabs/GET3D/pull/17
