### ISSUE TITLE
error for render image

### ISSUE THREAD

**Issue by yjcaimeow** [nv-tlabs/GET3D#122]
@SteveJunGao @zgojcic 

Hi, I follow your readme for rendering image from a mesh, i.e. `https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_all.py`

The original mesh is like this.
![image](https://user-images.githubusercontent.com/75470313/236395323-1f2b6e6d-76a7-411b-acd4-5b18c0664fdf.png)

But the rendered images have error obviously, like the following figure.
![image](https://user-images.githubusercontent.com/75470313/236395472-c1a93117-c4c0-4b2b-830d-f7b126dba509.png)
![image](https://user-images.githubusercontent.com/75470313/236395510-f7def483-42bd-4852-8e6c-a596b20f8cf8.png)

Could you please help me the bug?

Best regards,
Yingjie CAI

**Comment by yjcaimeow** [comment]
Bug is fixed via adding `bpy.ops.object.join()`.  Thanks again.

**Comment by jiahaoli95** [comment]
@yjcaimeow Hi, thanks for the issue. I ran into the same problem. Where did you insert `bpy.ops.object.join()` in the code? I tried to do that but either got an error or no effect at all. Thank you!
