### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by Sravanthgithub** [nv-tlabs/GET3D#123]
what is the suggested numpy version to run this project?

Because i have seen below 2 lines use some older numpy version. (np.float doesnt work in latest numpy versions)

mask = np.sum(img.astype(np.float), axis=-1, keepdims=True)
mask = (mask <= 3.0).astype(np.float)

**Comment by SteveJunGao** [comment]
Hi, @Sravanthgithub,

We're using numpy version `1.21.2` when training our model

**Comment by SteveJunGao** [comment]
Close this issue as haven't heard back for two months, please feel free to reopen it if you still find the problem!
