### ISSUE TITLE
How many views needed for inference ?

### ISSUE THREAD

**Issue by fefespn** [nv-tlabs/GET3D#124]
In the paper you mentioned that rendered training dataset is 24 random views for Cars&Char and 100 for Motorbike.
How much 2d images of the object you need for the inference ? the same amount ?
Did you tried to inference with less, maybe just 2-3 views ?

**Comment by fefespn** [comment]
Thanks ! My fault.

**Comment by fefespn** [comment]
Can't we start from an image (get the latent code of it in some way) and get the 3D result ?

**Comment by Bathsheba** [comment]
no

**Comment by fefespn** [comment]
Ok rhanks a lot for your hard work and long days !!
