### ISSUE TITLE
About latent variables

### ISSUE THREAD

**Issue by m-shuto** [nv-tlabs/GET3D#125]
In which files are the latent variables z_1 and z_2, which are input to the mapping network, generated? Also, it would be appreciated if you could explain how to determine the latent variables yourself and input them into GET3D.
Thanks.

**Comment by SteveJunGao** [comment]
The texture latent z is generated in [this line](https://github.com/nv-tlabs/GET3D/blob/master/training/training_loop_3d.py#L271), the geometry latent z is generated [here](https://github.com/nv-tlabs/GET3D/blob/master/training/loss.py#L53)

Both of them are sampled from a Normal distribution.
