### ISSUE TITLE
usage instructions

### ISSUE THREAD

**Issue by trusktr** [nv-tlabs/GET3D#127]
Total newb here. Seems that there are some assumptions that a dev already knows the stack being used.

Is there a step of commands we can use to try converting text to 3D, given we have input ready and we haven't cloned this repo yet? (i.e. from scratch)

**Comment by SteveJunGao** [comment]
Hi @trusktr,

Thanks for your interest to our project!

Unfortunately, we haven't released the code for text to 3D directly. There's an unofficial implementation that might work for you.  https://github.com/nv-tlabs/GET3D/pull/131

**Comment by SteveJunGao** [comment]
Close the issue for now, feel free to re-open it if the same question arises
