### ISSUE TITLE
pre-trained inference.py for book, cup, bag etc?

### ISSUE THREAD

**Issue by uniqueram** [nv-tlabs/GET3D#130]
Does pre-trained inference.py support other images also?

**Comment by SteveJunGao** [comment]
Hi @uniqueram,

This is a very good feature to add in the future! Right now, we only provided the pretrained models for chairs, motorbikes, tables and cars.

**Comment by SteveJunGao** [comment]
Close the issue for now, feel free to re-open it if the same question arises
