### ISSUE TITLE
Setting up PyTorch plugin "upfirdn2d_plugin"...

### ISSUE THREAD

**Issue by KDM777** [nv-tlabs/GET3D#132]
![image](https://github.com/nv-tlabs/GET3D/assets/69681273/54c68a33-980f-4da4-bbb7-757c91356da2)
When I turn the code, it stays in that state for 10 minutes.
CUDA version 11.1, PyTorch version 1.9.0, and Python version 3.8, please tell me why it doesn't work

**Comment by SteveJunGao** [comment]
Hi @KDM777,

This looks a bit weird to me... I haven't met this issue before. What's the cuda version your pytorch used?

**Comment by SteveJunGao** [comment]
Close the issue for now, feel free to re-open it if the same question arises
