### ISSUE TITLE
what is PATH_TO_RENDER_CAMERA to put for training

### ISSUE THREAD

**Issue by kenchen3000** [nv-tlabs/GET3D#133]
Hi,
I am wondering if there is place to download the data for PATH_TO_RENDER_IMG and PATH_TO_RENDER_CAMERA wrt to the training command below? thanks.
`python train_3d.py --outdir=PATH_TO_LOG --data=PATH_TO_RENDER_IMG --camera_path PATH_TO_RENDER_CAMERA --gpus=8 --batch=32 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0
`

**Comment by SteveJunGao** [comment]
Hi, 

Unfortunately, we couldn't provide the dataset with the licensing issue. You can follow our [readme](https://github.com/nv-tlabs/GET3D/tree/master/render_shapenet_data) to prepare the dataset by yourselves.

**Comment by SteveJunGao** [comment]
Close the issue for now, feel free to re-open it if the same question arises
