### ISSUE TITLE
Is there anyway to run GET3D with AMD GPUs / on Windows

### ISSUE THREAD

**Issue by mstahrirchi** [nv-tlabs/GET3D#136]
I was so excited to find this project, but no luck in running it!
I'm running an AMD RX 7900 XT and using Windows 11.

This article is the furthest I got regarding running GET3D on my system:
https://www.hpcwire.com/2022/11/28/porting-cuda-applications-to-run-on-amd-gpus/

I'd appreciate ANY insight.

**Comment by SteveJunGao** [comment]
Hi @mstahrirchi,

Unfortunately, our code requires NVIDIA GPU and Linux to run, I haven't tested it in AMD with Windows

**Comment by mstahrirchi** [comment]
@SteveJunGao, thanks for your quick response!
I've read through the issues here, and I got familiar with the basics of your code (btw, great job!)
I wanted to open a new issue to see if anyone had any tricks up their sleeves to expand the usability.
Cheers,
