### ISSUE TITLE
Google Colab for Artists/Game Designers

### ISSUE THREAD

**Issue by Delta-Ark** [nv-tlabs/GET3D#14]
Hi There,

Have had some good success with a dreamfields collab. Please see here: https://www.instagram.com/p/CjURPkWrMvh/ . Was actually able to import it into unreal; please see here: https://www.instagram.com/p/CjUZS2zuvRS/ . Would it be possible to get a colab of this work so that we, artists/game designers, can begin experimenting with it? Thank you!

**Comment by SteveJunGao** [comment]
Hi @Delta-Ark ,

Yes, we're working on it. If everything is ok with the licensing restrictions from the dataset our model is trained on, we will release the pretrained model and prepare a collab to try. Please stay tuned!

**Comment by Delta-Ark** [comment]
That's so exciting. Thank you!

**Comment by hyperific** [comment]
I would love to see this too as I don't have 8 high end GPUs lying around 😂😅

**Comment by hyperific** [comment]
Thanks very much! I'm really excited to dive in to this!

**Comment by Delta-Ark** [comment]
Sorry, I'm not sure how to use this collab. It says that the files are being saved somewhere, but I haven't connected my google drive to the collab and/or don't know how and/or don't see where it says to do this, so where are the files being saved?

I'm also getting errors like this:

```
Traceback (most recent call last):
  File "train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 46, in subprocess_fn
    inference_3d.inference(rank=rank, **c)
  File "/content/GET3D/training/inference_3d.py", line 76, in inference
    model_state_dict = torch.load(resume_pretrain, map_location=device)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/GET3D/get3d_release/shapenet_motorbike.pt'
```

**Comment by vrai17** [comment]
Creating output directory...
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
==> resume from pretrained path /content/GET3D/get3d_release/shapenet_car.pt
==> generate 
/content/GET3D/training/networks_get3d.py:430: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  camera_theta = torch.range(0, n_camera - 1, device=self.device).unsqueeze(dim=-1) / n_camera * math.pi * 2.0
[F glutil.cpp:338] eglInitialize() failed

**Comment by Remember12344** [comment]
have you solved this?

**Comment by Remember12344** [comment]
https://github.com/nv-tlabs/GET3D/issues/14#issuecomment-1543304123
anybody solved this issue?
