### ISSUE TITLE
How to set gamma and dmtet_scale for different data?

### ISSUE THREAD

**Issue by hwang1996** [nv-tlabs/GET3D#15]
Thanks for sharing your awesome work!

Since you gave different settings for different classes, I am wondering if you have any insight to tune the 'gamma' and 'dmtet_scale' in your training script? Currently we are trying to implement your framework to other datasets, your advice would be very helpful.

Thank you.

**Comment by hwang1996** [comment]
Thanks for your explanation!

Sorry I'm not familar with Shapenet, so the setting of `scale` during Shapenet rendering also confuses me. Is there any reason to give different `scale` for different classes? (`0.7` for chair and `0.9` for car)

Thank you.

**Comment by SteveJunGao** [comment]
I manually set these numbers by hand. 

The main reason is that the camera is always on the upper hemisphere, and the axis with maximum length for chairs is always the vertical one, but for cars, it is mostly the horizontal one; so if the maximum length for a chair is too big, then the object can go outside of the image plane. 

We generally hope the object scale is as large as possible to make the object large enough when we render it (so the camera can "see" more details) but we also need to make sure the object didn't go beyond the image plane (too large).

**Comment by hwang1996** [comment]
That makes sense, thanks!👍
