### ISSUE TITLE
Google Colab is not working

### ISSUE THREAD

**Issue by Yichuan0712** [nv-tlabs/GET3D#159]
The Colab to try out the code is not working now. To fix this, I have to replace all the 'RasterizeGLContext' with 'RasterizeCudaContext' in your repository.

**Comment by AfshinKoupaei** [comment]
Did it finally work after you changed to RasterizeCudaaContext ? or do still have issues? 
I also had to change the version of the torch and its dependencies to newer versions, did you experience any issues with that as well ?
