### ISSUE TITLE
About the pretrain model

### ISSUE THREAD

**Issue by HappyBoBo0331** [nv-tlabs/GET3D#16]
Maybe it's my fault that I didn't find the download address of the pre training model. This training scale is too large for me. I want to directly infer to see the effect of the network.I want to ask if there is a trained model that can be directly used for inference.

**Comment by SteveJunGao** [comment]
Hi @HappyBoBo0331 ,

We haven't released the pretrained model yet. We're working on this to resolve the licensing restrictions, and it should be ready very soon (hopefully by the end of next week), please stay tuned!

**Comment by HappyBoBo0331** [comment]
Thank you for making me look forward to next week! It must have been a wonderful week! Once again, pay tribute to your work!

**Comment by taruntiwar** [comment]
Waiting for pretrained model. Thanks

**Comment by SteveJunGao** [comment]
Hi, we have released the pretrained models [here](https://github.com/nv-tlabs/GET3D/tree/master/pretrained_model)

**Comment by taruntiwar** [comment]
Hi @SteveJunGao Thanks for sharing pretrained model, I tested inference with a few cases, and I'm getting very low poly in mesh, Please guide me on how I can improve this thanks.

 
![image1](https://user-images.githubusercontent.com/108065874/195800445-cfa58ff4-ec71-41b3-afeb-20fb86e615ca.png)
![image](https://user-images.githubusercontent.com/108065874/195800456-bf409883-c2dd-4065-856b-64606aea2f02.png)

**Comment by SteveJunGao** [comment]
Hi @taruntiwar,

This is the resolution we're using when we generate the results in our paper. 

There're several ways you can improve the results:

1. Increase the inference resolution by passing `--tet_res 100` (or give it an even higher value), but in this case, you need to first generate the tet grid following this [readme](https://github.com/nv-tlabs/GET3D/tree/master/data)

2. Finetune the model with the grid resolution you're working on, as the model we provided is only trained on the grid resolution of 90, so it might be some mismatch when you evaluate it in higher resolution, fine-tuning it might resolve some mismatch.

3. Another thing you can do is do mesh subdivision after [this line](https://github.com/nv-tlabs/GET3D/blob/master/training/networks_get3d.py#L254), it won't affect the texture part, but will directly give the results with higher poly.

Hope this can help!
