### ISSUE TITLE
Regarding dataset

### ISSUE THREAD

**Issue by weiyao1996** [nv-tlabs/GET3D#2]
This is a very good work. Congratulations! Would you please provide relevant experimental datasets, such as the _House_ dataset (563 shapes) collected from Turbosquid? Thanks in advance.

**Comment by SteveJunGao** [comment]
Unfortunately, we are not able to release the Turbosquid data, due to licensing restrictions of the data.

**Comment by epajarre** [comment]
If it is not too much trouble, a list of the used assets on Turbosquid would be interesting.
