### ISSUE TITLE
Text-Guided 3D Synthesis

### ISSUE THREAD

**Issue by AmanKishore** [nv-tlabs/GET3D#20]
Hi @SteveJunGao thank you for all your help!
When you release the pretrained model (Issue #16) will you also be releasing the weights for the fine-tuned model on CLIP?
Excited to continue working on this!

**Comment by lalalune** [comment]
Hi @AmanKishore 
We're doing this too, but we have opted for a 2D side-view generation using standard Stable Diffusion (with tags to ensure a white background) that then gets passed in here. The process here isn't generative in the same way that the CLIP-guided models are.

We are also experimenting with 3D Stable Dreamfusion (https://github.com/ashawkey/stable-dreamfusion) but it is much much slower and lower quality results. I believe that using SD to generate your image and then running it through GET3D will be 10-20x faster and higher quality result, provided you have sufficiently trained the model on similar object classes.

**Comment by SteveJunGao** [comment]
Hi, @AmanKishore ,

That's definitely one thing on my plan! Unfortunately, I may not have enough time to release the fine-tuned model on CLIP for text-guided 3D synthesis before CVPR, I expect this part will be released after CVPR when I get more free time to clean the code. 

Hi @lalalune ,

It would be awesome to try this direction! Please let me know if you have any cool results on it!

**Comment by AmanKishore** [comment]
That's great! I'd love to chat @lalalune! Sounds like an interesting use case!

**Comment by SteveJunGao** [comment]
Hi @AmanKishore,

I didn't have an exact timeline for this part right now, if you urgently need that part I recommend you go to this [codebase](https://github.com/rinongal/StyleGAN-nada), our implementation for text-guided 3D synthesis is based on this code.

**Comment by AmanKishore** [comment]
Thank you! And was the training data mostly Shapenet?

**Comment by SteveJunGao** [comment]
Yes, the training data is mostly shapenet!
