### ISSUE TITLE
Remove hardcoded values for datasets and add args for dataset input

### ISSUE THREAD

**Issue by lalalune** [nv-tlabs/GET3D#22]
Right now there are many references in the code to specific datasets, as well as a data_camera_mode option that takes a dataset name which gets handled with some complex if statements at various points in the training code.

Raising the issue here to remove these specific requirements and generalize modes ("object", "human", etc). Maybe we pass a configuration file in so that future researchers can add their own custom parameters.

(by the way, I'm working on a PR for this!)

**Comment by tomtang12** [comment]
![image](https://user-images.githubusercontent.com/115465656/194848326-706f93d7-21f2-46b5-b2be-0a1d4a7e78f6.png)
![image](https://user-images.githubusercontent.com/115465656/194848744-f0a7cadf-7674-4d46-8549-4c3b36cfd189.png)

Image can't load to Training also... 
Has anyone encountered this problem ,Thanks

**Comment by SteveJunGao** [comment]
Hi @lalalune ,

That's a great suggestion! 

I didn't consider this when I started coding my project a long time ago, having a config file for different datasets is definitely one good approach to improve the code structure! Thank you for providing this PR!

**Comment by SteveJunGao** [comment]
Hi @tomtang12 

Can you explain more about how are you planning to use the code? We are doing unconditioned generation in our model, so there won't be a 'test' set. 

To load the training images, I think you will need to adapt the dataloader for your custom dataset. Right now our code only supports loading the images rendered from our rendering scripts on shapenet

**Comment by AnjieCheng** [comment]
Hi @SteveJunGao,

I'm wondering if there are plans to release your train/val/test model ids for ShapeNet evaluation. 

Thanks!

**Comment by SteveJunGao** [comment]
Hi @AnjieCheng 

It has already been released [here](https://github.com/nv-tlabs/GET3D/tree/master/3dgan_data_split) ;)

**Comment by AnjieCheng** [comment]
@SteveJunGao 
Ooops, missed it. Thank you so much!

**Comment by tomtang12** [comment]
> Hi @tomtang12
> 
> Can you explain more about how are you planning to use the code? We are doing unconditioned generation in our model, so there won't be a 'test' set.
> 
> To load the training images, I think you will need to adapt the dataloader for your custom dataset. Right now our code only supports loading the images rendered from our rendering scripts on shapenet
![image](https://user-images.githubusercontent.com/115465656/195042380-917c0dca-fb68-44c3-a4f3-259d5c507c60.png)
![image](https://user-images.githubusercontent.com/115465656/195042525-7ca6195c-da89-48b5-bf2b-d2cad8ef6254.png)
![image](https://user-images.githubusercontent.com/115465656/195043271-2b2317a5-5d5e-4fcd-aecc-2225e9eafd38.png)
![image](https://user-images.githubusercontent.com/115465656/195043368-90f48ac5-3a2f-43cc-8440-5dc5d754c450.png)

I Need 3D scanning, numerous photographs of my dog is another way to create a 3D model.
sorry i think too much.

**Comment by SteveJunGao** [comment]
Hi @tomtang12 

I think you can try this one https://github.com/NVlabs/nvdiffrec (it's more close to what you want)

**Comment by tomtang12** [comment]
> Hi @tomtang12
> 
> I think you can try this one https://github.com/NVlabs/nvdiffrec (it's more close to what you want)

Many thanks @SteveJunGao！

So "nvdiffrec" is better then instant-ngp.
I was just finish trying to get "instant-ngp" installed...
Today Wasted all day installing "instant-ngp"...

thanks for your advice

instant-ngp
[instant-ngp](https://github.com/NVlabs/instant-ngp)

**Comment by SteveJunGao** [comment]
Thanks!

I close the issue for now, feel free to reopen it if you have any further questions!
