### ISSUE TITLE
Issue on training

### ISSUE THREAD

**Issue by Freja71122** [nv-tlabs/GET3D#24]
Hi There,

I followed the training guide in README，and I met this problem: `TypeError: unsupported operand type(s) for /: 'Nonetype' and 'int'`
Do you have any ideas how to fix this problem?

![HY6R M`ZU4G~5WPT2KS _V4](https://user-images.githubusercontent.com/101861465/195010469-bd31fe73-273b-4777-b467-68d84023168f.png)

My training script is like this:
![image](https://user-images.githubusercontent.com/101861465/195031167-f5aa1bb6-54cc-4a49-9571-284100299627.png)

**Comment by lalalune** [comment]
That looks like the error where it's not actually finding the training data. It's expecting an int num items but it's null.

I suspect that this is some weirdness with the CLI input and your path -- maybe you need ./ori_data/ ?

Otherwise could be a version mismatch in dependencies but I've only gotten this issue from training path mismatch

IMO add something to the script that checks if the path exists and errors out if it does not

**Comment by Freja71122** [comment]
![image](https://user-images.githubusercontent.com/101861465/195070882-0767e6ff-54cb-4b7c-98ef-f707b16b36c0.png)

The path is correct, and it has found image files. Do you have any other ideas how to fix this problem?

**Comment by Freja71122** [comment]
In addition, it takes about a whole day for each syn_id to render, and it will take about a month for all data to be rendered. Is it normal to be so slow?

**Comment by SteveJunGao** [comment]
Hi @Freja71122

Yes, the rendering is slow, I didn't optimize that part, you can take a look at this [MR](https://github.com/nv-tlabs/GET3D/pull/17) to see whether it can help you

**Comment by Freja71122** [comment]
It hangs after rendering one `syn_id` 02958343. Is it normal?

My script is `python render_all.py --save_folder PATH_TO_SAVE_IMAGE --dataset_folder PATH_TO_3D_OBJ --blender_root PATH_TO_BLENDER`

![image](https://user-images.githubusercontent.com/101861465/195227201-3a44a145-e79c-44ef-9613-9d5789a02d51.png)

**Comment by SteveJunGao** [comment]
Emmm, 

this is not normal, it shouldn't hang there.. do you have any other error messages?

**Comment by Freja71122** [comment]
No any error message... Should I restart `python render_all.py`? Will it render syn_id 02958343 again? And how to make it not hang again?

**Comment by Siziff** [comment]
I have the same error when preparing data. How long did it take you to prepare the data? I have been processing data for more than 24 hours and I haven't even prepared half of it. I work on a server with one V100 graphics card. How long does it take?
![image](https://user-images.githubusercontent.com/42972554/195296065-a644d5ad-650f-4a38-ab62-9b785198d83f.png)

**Comment by Freja71122** [comment]
I work on 8 V100 graphics card, and it takes more than 24 hours for one syn_id dataset. There are three synset, so I guess it will take another 2 days.

**Comment by SteveJunGao** [comment]
Yes, the code I wrote for blender is not optimized, so it can take 2-3 days to render one synset. 

You can check this [MR](https://github.com/nv-tlabs/GET3D/pull/17) to see whether it can speed things up

**Comment by Freja71122** [comment]
Thank you! @SteveJunGao

I close this issue, since I have got enough help and information about initial question.

**Comment by efyphil** [comment]
@Freja71122  Hi, I have the same error as you. Can you tell me exactly where to delete the pkl file? I already deleted it in the cache folder

**Comment by Kuang-Hiu** [comment]
> Thank you for your reply. I have solved it. The path is correct, and the reason is there are past pkl files in the cache, so the correct data is not loaded.

I have same your issue but I don't understand your solved. Can you explain more detail?
Thanks
