### ISSUE TITLE
Multiple classes in same checkpoint

### ISSUE THREAD

**Issue by lalalune** [nv-tlabs/GET3D#27]
I am hoping to train a general model on 3D understanding beyond just a single class or range of classes.

I am doing this by resuming training on a checkpoint while swapping out datasets, however I am unsure of the limitations here.

Will training on a wider range of data make the model worse at individual tasks? Or is there otherwise any reason *not* to do this?

**Comment by lalalune** [comment]
Took my motorbike model, trained it on ShapeNet knives for an hour:
![image](https://user-images.githubusercontent.com/18633264/195123014-5f2af60d-8109-4967-b2b2-357b2cb56eaf.png)

Not bad!

**Comment by SteveJunGao** [comment]
Wow, the results are not bad!

I tried to train the model on 13 Shapenet Core categories, and it also works. 

The easiest way to achieve training on multi-categories is through merging all the datasets together and treat them as "one category", this should already give you a descent performance.  

Another way is doing class-conditioned shape generation, e.g. when generate the shape, you can feed in the one-hot class label into the generator

**Comment by lalalune** [comment]
Thanks, trying this now

**Comment by renrenzsbbb** [comment]
> 

Thanks for your great work. I have a question that you can train one model to generate different kinds of object. Why do you train one model for one object. Thanks.

**Comment by minsu1206** [comment]
@whoopee

Hi. Did you find proper gamma value for many classes? I hope you share some tips on it.
I struggle to train GET3D on Objaverse animals dataset (includes 10 categories), but I failed to train with gamma=400, 500, 1600.

Thanks.
