### ISSUE TITLE
training on FFHQ?

### ISSUE THREAD

**Issue by renrenzsbbb** [nv-tlabs/GET3D#28]
Thanks for your great work. I find that you compare your result with eg3d in paper and claim that your result is better than it in 3 dataset. I have a question that GET3D is better than EG3D in human face dataset like FFHQ or CelebA.

**Comment by SteveJunGao** [comment]
Hi @renrenzsbbb ,

We haven't tried on FFHQ or CelebA dataset in GET3D. One limitation of our work is that it is hard to resolve depth from multi-view images using DMTet (assuming no 2D silhouettes), and FFHQ (or CelebA) is mainly for frontal faces not full 360 coverage of the whole head, thus it might be hard for GET3D to generate reasonable shapes from it. 

I'd love to see how GET3D can perform on FFHQ (or CelebA) if someone can try it!

**Comment by SteveJunGao** [comment]
Close for now, feel free to reopen it if you have any further questions
