### ISSUE TITLE
not found camera root

### ISSUE THREAD

**Issue by zhaoyang6** [nv-tlabs/GET3D#29]
there is a problem when I train the model using Anaconda virtual envirentment:
![error](https://user-images.githubusercontent.com/29686235/195314435-c14e7d36-660d-4c61-a715-39449d0450df.PNG)

**Comment by SteveJunGao** [comment]
Hi @zhaoyang6 ,

Can you provide the training command you used? it seems you used a wrong path for camera from this result

**Comment by SteveJunGao** [comment]
Oh, you need to set camera path to be `./dataset/camera`  ;)

**Comment by zhaoyang6** [comment]
I have changed this command as you say, but there is another problem as following:
![problem](https://user-images.githubusercontent.com/29686235/195491898-12e71047-59f7-4faa-9106-01a889e6b781.PNG)

**Comment by Freja71122** [comment]
@zhaoyang6  It seems you used a wrong path for img from this result. Img path should end with syn_id.

u can refer to this pic:
![image](https://user-images.githubusercontent.com/101861465/195509102-7eab1bd9-530b-49a8-ab1e-a24cebbac44f.png)

**Comment by zhaoyang6** [comment]
@Freja71122 I have checked the command and it is correct. And I use print function to output some information. Maybe it is caused by read a bad image. What exactly caused it, I'm not sure.

**Comment by Freja71122** [comment]
It will print folder number and image number before training, can u show the print infos?

like this
![C6X7 7Y8@9@$X2FWHFG@YD](https://user-images.githubusercontent.com/101861465/195555137-bfad407e-3e92-4e49-a627-a63edecb72c5.png)

**Comment by SteveJunGao** [comment]
@zhaoyang6,

From the log you showed, it seems the model can find the dataset you're training on. 

Can you add a `try` at [this line](https://github.com/nv-tlabs/GET3D/blob/master/training/dataset.py#L290) to see which image has the problem?

```python
try: 
    ori_img = cv2.imread(fname, cv2.IMREAD_UNCHANGED)
    img = ori_img[:, :, :3][..., ::-1]
except:
    print(fname)
```

**Comment by zhaoyang6** [comment]
@SteveJunGao As you say, the log is:
Constructing networks...
fname:dataset/img/03790512/97bb8c467f0efadaf2b5d20b1742ee75/transforms.json
fname:dataset/img/03790512/47054c1839830834a88e8cb97b773125/transforms.json
fname:dataset/img/03790512/896f688e07909b9b893e67220bf9be7/transforms.json
fname:dataset/img/03790512/8ed4bdaf0c8b88ea8b31e74d456742c7/transforms.json
fname:dataset/img/03790512/acd49452b452cf2f3ab3dfa44f5fab01/transforms.json
fname:dataset/img/03790512/5df0478fd19f0c175af8505fd49bb4ca/transforms.json
Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
fname:dataset/img/03790512/97bb8c467f0efadaf2b5d20b1742ee75/transforms.json

**Comment by SteveJunGao** [comment]
Thanks for providing this error information!

It's indeed a bug in the code due to a recent MR, I just fixed it and pushed the new changes, can you pull again and see whether the problem still exists?
