### ISSUE TITLE
Ability to reduce the video memory requirements for the result output

### ISSUE THREAD

**Issue by NeuroLord** [nv-tlabs/GET3D#3]
I have ~~a dream...~~ my good old 3060 with 12 GB of memory, and this project needs all 16 to get results. Is it possible to reduce its appetite by a measly 4 gigabytes?

**Comment by SteveJunGao** [comment]
Yes, there're many ways to reduce memory consumption:

1. You can render lower resolution images by setting `--img_res 512` or `--img_res 256`, this can reduce the memory a lot
2. You can also reduce the resolution of the tetrahedron grid by setting `--tet_res 70` or `--tet_res 60` 
3. You can further reduce the resolution for triplane resolution by setting `--tri_plane_resolution 128` or `--tri_plane_resolution 64`

I think by reducing these resolutions, the memory should be able to go less than 12GB easily (with some sacrifices in performance)
