### ISSUE TITLE
Support for DDP with multi nodes

### ISSUE THREAD

**Issue by Freja71122** [nv-tlabs/GET3D#30]
Hi there,

I found the code can only run with multi gpus in one node, if there are supports for multi gpus in multi nodes?

@SteveJunGao

**Comment by SteveJunGao** [comment]
Hi @Freja71122,

Unfortunately, I haven't tried to run the code on multi-nodes, it only supports multi-gpus for now. It would be great if someone in the open-source community can extend it to multi-nodes

**Comment by SteveJunGao** [comment]
Hi @Freja71122, any updates on this issue? do you have further questions? or it's good to close this?
