### ISSUE TITLE
Run inference on a specific image

### ISSUE THREAD

**Issue by lalalune** [nv-tlabs/GET3D#31]
Right now, inference is run on the eval images.

It'd be awfully handy to be able to assess arbitrary images by passing one to the CLI!

**Comment by Freja71122** [comment]
Hi @lalalune , it seems they don't need any images to run inference.

u can refer to https://github.com/nv-tlabs/GET3D/issues/25#issuecomment-1274812336

**Comment by SteveJunGao** [comment]
Yes, inference doesn't need the specific image as input, we're doing unconditional 3D shape generation.

You can check this [inference code](https://github.com/nv-tlabs/GET3D/blob/master/training/inference_3d.py#L94)  for more details

**Comment by lalalune** [comment]
Ah, I see! Probably should spend more time reading :)
Is there an example of CLIP guidance? I read in the paper but could not find in the code, although it incidates that "house" was generated with "house" as a CLIP guide. Forgive me for noobishness, I am a reasonably competent engineer but new to AI :)
