### ISSUE TITLE
Volume Sub-division

### ISSUE THREAD

**Issue by anchit** [nv-tlabs/GET3D#33]
Where is subdivision used in the code? The function batch_subdivide_volume doesn't seem to be used.

**Comment by SteveJunGao** [comment]
Hi, we haven't added that part to the training of GET3D, we're working on cleaning it. 

The main functions should already be there, and you can train the GET3D without volume subdivision.

**Comment by SteveJunGao** [comment]
Hi @anchit, any updates on this issue? do you have further questions? or it's good to close this?
