### ISSUE TITLE
Can this model fit Google Drive?

### ISSUE THREAD

**Issue by qfb594** [nv-tlabs/GET3D#37]
wget https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl

Please send me the download link below, thank you!

**Comment by SteveJunGao** [comment]
Hi @qfb594,

What's the issue you're facing? Is the link not working?

We couldn't release this checkpoint by ourselves due to the licensing issue. If the link is not working, you can follow [this issue](https://github.com/nv-tlabs/GET3D/issues/5) to see whether it's helpful to you.

**Comment by qfb594** [comment]
{"requestStatus":{"statusCode":"SUCCESS","requestId":"5e6dc3de-9ab7-4111-956d-d0f6e9907578"}}  那个链接我打开是这样的 
尊敬的作者您好，我是3d模型制作者，并不会专业的编程，我是想在win上运行这个程序，想把这个模型下下来，可是这样的提示 不知道该怎么下载了。所以找到你求助。

**Comment by SteveJunGao** [comment]
Hi,

If you only want to run the model on a pretrained checkpoint, you don't need this file, you can ignore this file ;)  (it's only required when you want to evaluate the performance)

You can also try on [Google Colab](https://colab.research.google.com/drive/1AAE4jp39rXhW2zmlNwpWkvDPULugIXfk?usp=sharing) to run the model, it might be easier to use, as you don't need to setup anything on your local machine.

**Comment by qfb594** [comment]
Ok, thank you very much！
