### ISSUE TITLE
Where is the generated model? Is it fbx or obj?

### ISSUE THREAD

**Issue by qfb594** [nv-tlabs/GET3D#38]
![QQ浏览器截图20221015161529](https://user-images.githubusercontent.com/48076384/195976960-626b44c4-2a49-4f68-bbb7-10e221132506.png)
Hi
Where is the generated model? Is it fbx or obj? If not, how can I use the generated 3d mesh model?

If I train the model myself, what do I need? A lot of png, or a lot of mp4 videos?

Do you have a specific use tutorial?

**Comment by SteveJunGao** [comment]
Hi, the generated model will be obj format, you can check the folder called `save_inference_results/shapenet_chair/inference/texture_mesh_for_inference` it will contains all the objs files we generated. 

If you want to train the model by yourselves, you can follow our [readme](https://github.com/nv-tlabs/GET3D/blob/master/README.md) to prepare the dataset (a lot of rendered images), and train it. 

I don't have a specific use tutorial for now, I hope the Google Colab is sufficient to test our model

**Comment by SteveJunGao** [comment]
Hi @qfb594, any updates on this issue? do you have further questions?

**Comment by qfb594** [comment]
I don't understand, I want to generate a 3d model of a cat, I need to provide a lot of cat pictures or videos into the program? Or do I just need to type in the cat keyword and it will be generated automatically?

**Comment by SteveJunGao** [comment]
Hi @qfb594, to clarify it a bit, our model needs to first be trained on a large amount of 2D data (with cameras), then it can generate 3D shapes by randomly sampling on the latent space. 

The pretrained models we provided are only for cars/chairs/motorbikes/tables, we didn't release a model for cats, so you need to train on it if you want to generate things like that. Typing a random keyword and generating corresponding 3D shapes is not something we can do (we didn't claim it in our paper and this github repo), the experiments we did is: the user gives a related keyword on a specific category and we finetune our 3d generative model to produce 3D shapes, but this needs to have a well-trained 3D generative model to start with. 

You can check more details about our paper [here](https://nv-tlabs.github.io/GET3D/assets/paper.pdf)

**Comment by qfb594** [comment]
Ok, I understand, thank you, hope to develop more models for external use in the future, wish your code is getting better and better.
