### ISSUE TITLE
Bug in inference with lower resolution

### ISSUE THREAD

**Issue by XinYu-Andy** [nv-tlabs/GET3D#39]
Hi,
Thanks for you awesome work!
I am trying to use your code to train the model with image resolution = 512x512. However, it seems this [line](https://github.com/nv-tlabs/GET3D/blob/18c35f12c9e47124930d4e036d986eebcc543bac/training/inference_3d.py#L64) of code 
always assumes the resolution with 1024x1024, and thus I cannot do inference for my trained model.  Maybe it should be fixed~

**Comment by SteveJunGao** [comment]
Hi @XinYu-Andy ,

Can you provide more error information so I can look at it? Yes, I hardcoded the inference resolution to 1024x1024, but it shouldn't be a problem for the generator, as during inference we can generate any image resolution we want (it's just rendering the images). The only problem I can think of is the discriminator, which needs to use the `img_resolution` to define its architecture.

**Comment by XinYu-Andy** [comment]
> Hi @XinYu-Andy ,
> 
> Can you provide more error information so I can look at it? Yes, I hardcoded the inference resolution to 1024x1024, but it shouldn't be a problem for the generator, as during inference we can generate any image resolution we want (it's just rendering the images). The only problem I can think of is the discriminator, which needs to use the `img_resolution` to define its architecture.

**RuntimeError: Error(s) in loading state_dict for Discriminator:
        Missing key(s) in state_dict: "b1024.resample_filter", "b1024.fromrgb.weight", "b1024.fromrgb.bias", "b1024.fromrgb.resample_filter", "b1024.conv0.weight", "b1024.conv0.bias", "b1024.conv0.resample_filter", "b1024.conv1.weight", "b1024.conv1.bias", "b1024.conv1.resample_filter", "mask_b1024.resample_filter", "mask_b1024.fromrgb.weight", "mask_b1024.fromrgb.bias", "mask_b1024.fromrgb.resample_filter", "mask_b1024.conv0.weight", "mask_b1024.conv0.bias", "mask_b1024.conv0.resample_filter", "mask_b1024.conv1.weight", "mask_b1024.conv1.bias", "mask_b1024.conv1.resample_filter".**

It would work for me if I modify the code as follows:
`common_kwargs = dict(c_dim=0, img_resolution=training_set_kwargs['resolution'], img_channels=3)`

**Comment by XinYu-Andy** [comment]
By the way, can I ask how many epochs you have trained for Shapenet chair class? Because I am using RTX3090 instead of A100, I want to check if my training goes in the correct way. Thank you!

**Comment by SteveJunGao** [comment]
Thanks for providing the error information!

I pushed a fix to GitHub, you can pull it again to check.

Regarding the training epochs: We count the number of images the discriminator sees in this codebase (you can check the output from the log, or see it from the tensorboard). Generally speaking, the model can get quite a good performance with 3000-5000kimgs (we have seen sometimes it can get better with more training, e.g. 10000kimages). We also have a validation set, we pick the model that achieves the best FID score on the validation set for testing on test set.

**Comment by XinYu-Andy** [comment]
> Thanks for providing the error information!
> 
> I pushed a fix to GitHub, you can pull it again to check.
> 
> Regarding the training epochs: We count the number of images the discriminator sees in this codebase (you can check the output from the log, or see it from the tensorboard). Generally speaking, the model can get quite a good performance with 3000-5000kimgs (we have seen sometimes it can get better with more training, e.g. 10000kimages). We also have a validation set, we pick the model that achieves the best FID score on the validation set for testing on test set.

Thanks! I will close this issue.
