### ISSUE TITLE
question about setting blender 

### ISSUE THREAD

**Issue by amiltonwong** [nv-tlabs/GET3D#4]
Hi, @SteveJunGao ,

According to the [steps](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/README.md), the following two lines are just used for ensuring the existence of pip and numpy:
```
./python3.7m -m ensurepip
./python3.7m -m pip install numpy 
```
Do we need to specify the location of bpy module, as it is needed [here](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py#L10), when executing `render_all.py` ?

When I execute
```
python render_all.py --save_folder /media/root/data2/ShapeNet/render_view --dataset_folder /media/root/data2/ShapeNet/ShapeNetCore.v1 --blender_root /root/Downloads/blender-2.90.0-linux64/2.90/python/bin
``` 

I got the following error:
```
sh: 1: /root/Downloads/blender-2.90.0-linux64/2.90/python/bin: Permission denied
```

Any hints to solve this issue?

Thanks~

**Comment by SteveJunGao** [comment]
Hi @amiltonwong ,

Regarding the `bpy`, you don't need to specify the location for it, as the script `render_shapenet.py` is running inside Blender's python, and it will find the `bpy` automatically.

Regarding the error :
```bash
sh: 1: /root/Downloads/blender-2.90.0-linux64/2.90/python/bin: Permission denied
```
It seems you don't have access to the blender file you downloaded, can you double check whether you have access to it? 

Also, to see more error message, you can remove ` >> tmp.out` from the command in this [line](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_all.py#L41) and it will print all the output from blender.

Hope this can help!

**Comment by amiltonwong** [comment]
Hi, @SteveJunGao ,

Thanks for your reply. I've fixed the problem and figured out it's the wrong configure in my blender.

One more question, does the scales [here](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_all.py#L33) have some typos? Two 0.9 scale values occur.

Thanks~

**Comment by saisurbehera** [comment]
How did you get it working @amiltonwong ?

**Comment by SteveJunGao** [comment]
@amiltonwong the scale is correct, we normalize all the chairs to the length of 0.7, car & motorbikes to the scale of 0.9, to get the best view of the object when rendering it.

**Comment by SteveJunGao** [comment]
I close the issue now, if have any updates or further questions related to this issue, feel free to re-open it!

Thanks for trying the code!

**Comment by saisurbehera** [comment]
Do you know how much time this process takes? I am seeing about 14612 blender runs.

**Comment by SteveJunGao** [comment]
It depends on the capacity of your GPU card ;) 

You can compute the time by (TIME_PER_OBJECT * N_OBJECT)

**Comment by saisurbehera** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/42232832/193436299-1dae1c9c-455b-415a-94fd-7779146c497b.png">
It is only using a small parts of the GPU

**Comment by SteveJunGao** [comment]
Yes, the rendering is not GPU intensive. You can also run multiple processes in one GPU such that your GPU utilization can be higher

Note that, you only need to render the dataset once, after that you can train many different models using this rendered dataset.

**Comment by Freja71122** [comment]
> --blender_root /root/Downloads/blender-2.90.0-linux64/2.90/python/bin

--blender_root should not be `xxx/blender-2.90.0-linux64/2.90/python/bin`, it should be `xxx/blender-2.90.0-linux64/blender`

**Comment by jpainam** [comment]
I got `14611` items preprocessed. and not `14612`, one item is missing and I've opened an issue about it at #154
