### ISSUE TITLE
About the results of the pretrained model

### ISSUE THREAD

**Issue by HappyBoBo0331** [nv-tlabs/GET3D#41]
I'm so sorry to bother you again. But I believe that you are so enthusiastic that you could solve my confusion.
I infer GET3D with the pretrained weight named shapenet_xx.pt and others on colab. But the results is not as good as your presentation, especially the 3D mesh of motorbikes. The stickiness of details is high. Even so, it's a good work. The steps i took are as your readme file. Is there anything i missed or ignored?  or maybe i should train the model by myself?

**Comment by SteveJunGao** [comment]
Hi @HappyBoBo0331,

Can you show some results of what you get, so I can double check? Probably you need to look at more samples to get good ones, right now the code I shared is generating random samples from the prior distribution.

**Comment by Agentvfx** [comment]
> Hi @HappyBoBo0331,
> 
> Can you show some results of what you get, so I can double check? Probably you need to look at more samples to get good ones, right now the code I shared is generating random samples from the prior distribution.

Is there a way to input a personal image to generate the 3D model of that, or this is just one the samples given?

**Comment by Siziff** [comment]
![Untitled](https://user-images.githubusercontent.com/42972554/196366572-75d33d9f-f1fd-42f9-be49-25770615c7b1.png)
If anyone have the same problem while Inference ?

**Comment by Siziff** [comment]
![image](https://user-images.githubusercontent.com/42972554/196374752-633031e5-6945-4322-a512-a4d3dd6bd95e.png)
If anyone have the same problem while inference?

**Comment by SteveJunGao** [comment]
Hi @HappyBoBo0331,

I just realized this issue was closed, Has your problem been resolved? could you show something that doesn't look good to you? I can double-check to see where the discrepancy is.

**Comment by HappyBoBo0331** [comment]
I appreciate your attention so much. However, it seems that I have to work on other cases recently. Although my current demand for GET3D is not so strong and urgent, I chose some sample pictures to explain my confusion. Obviously, the 3D model of the cycle part and the handle part looks rough. The UV mapping also didn't perform as well as the presetation in the paper. I don't know if this is caused by my incorrect settings on the colab. If it is, please let me know. I hope this will help GET3D stronger or help other followers. Thanks for you work and your patience again!
![image](https://user-images.githubusercontent.com/62469725/199389199-f62bafd2-49 9f-42b9-a51d-689ef5e7c714.png)
![image](https://user-images.githubusercontent.com/62469725/199389379-c2ed4116-8161-4044-893f-7da808b2367c.png)
