### ISSUE TITLE
Random Seed

### ISSUE THREAD

**Issue by AmanKishore** [nv-tlabs/GET3D#45]
Hi @SteveJunGao how can I use --seed to change the order of output from inference?

**Comment by SteveJunGao** [comment]
Hi @AmanKishore,

What do you mean "the order of output from inference"? Is this something like which shape comes first, and which comes last? The `--seed` arguments basically allows to generate the shapes with different random seed

**Comment by AmanKishore** [comment]
Was a bug on my side! Sorry about that
