### ISSUE TITLE
Deformation prediction

### ISSUE THREAD

**Issue by XinYu-Andy** [nv-tlabs/GET3D#46]
Hi,
Thanks for your great work! I have a question about the deformation prediction:
I noticed that in your previous work (i.e. DEFTet and DMTet), you used GCN to predict the deformation. However, in GET3D, you use a simple MLP as your network architecture. Could you please give some explainations for this modification? 
Thank you.

**Comment by SteveJunGao** [comment]
Hi @XinYu-Andy,

We hope to make the model as simple as possible in GET3D, so we just use a simple MLP to predict the deformations and we find it can already give us a great performance. It would be cool to see how GCN can work with GET3D (we haven't tested this setting in our experiments) :)

**Comment by XinYu-Andy** [comment]
> Hi @XinYu-Andy,
> 
> We hope to make the model as simple as possible in GET3D, so we just use a simple MLP to predict the deformations and we find it can already give us a great performance. It would be cool to see how GCN can work with GET3D (we haven't tested this setting in our experiments) :)

Thanks! Have you tried single-view recounstruction using this framework? I am wondering if it could work by simply conditioning on a single-view image.

**Comment by SteveJunGao** [comment]
We haven't tried it, but it would be great to see how this can work with GET3D!

**Comment by XinYu-Andy** [comment]
> We haven't tried it, but it would be great to see how this can work with GET3D!

ok~thanks!

**Comment by Siziff** [comment]
Hi @XinYu-Andy ,
The GCN article referenced in the article uses information about x (a point cloud or a coarse voxelized shape) but in GET3D, information about voxels is not recorded anywhere.
I would like to try to implement GCN in GET3D, but I don't know what to do with this variable, could you give an explanation of how you did it or ideas how it can be done ? 

![image](https://user-images.githubusercontent.com/42972554/198001377-cb0a2825-e9b6-47bb-b4c6-0609adcae454.png)


> Hi, Thanks for your great work! I have a question about the deformation prediction: I noticed that in your previous work (i.e. DEFTet and DMTet), you used GCN to predict the deformation. However, in GET3D, you use a simple MLP as your network architecture. Could you please give some explainations for this modification? Thank you.
