### ISSUE TITLE
2d images to 3d   model

### ISSUE THREAD

**Issue by Siziff** [nv-tlabs/GET3D#48]
Hello everyone, I did not find in the article a description of how to make 3d models from 2d pictures, just a little about the verbal description of the style. Logically, of course, it can be assumed that instead of a sample from the distribution, it is possible to submit a picture to the MLP input, but due to the closeness of the architecture, I could not do this experience. Perhaps someone has already tried to conduct a similar experience? Could you tell us how to do this on this project ?

**Comment by Siziff** [comment]
And one more little question, how can I view the architecture of the model with its parameters ? As far as I understand, the Generator in the project is subclass from the torch.nn.Module class and the architecture is not explicitly specified. Could you suggest a little instruction on how I can view it?

**Comment by SteveJunGao** [comment]
Hi @Siziff,

We haven't tried this in GET3D, two related references that might be helpful for you:

1. [EG3D](https://nvlabs.github.io/eg3d/) has an experiment doing image inversion (from 2D images to 3D models), you can follow it and plugin the same pipeline to our code

2. [PVT](https://arxiv.org/abs/2106.05744) is a well-known method for GAN's inversion, it has many cool ideas to make inversion working better
