### ISSUE TITLE
"Connection refused" error when training

### ISSUE THREAD

**Issue by anna-debug** [nv-tlabs/GET3D#49]
Hi, 
I want to train this network on my own dataset (which I have processed using the provided rendering scripts) however I get an "ConnectionRefusedError: [Errno 111] Connection refused" error and an "NotImplementedError" raised in the discriminator_architecture script when I run the training. What might be the issue here?

![Screenshot from 2022-10-20 12-49-13](https://user-images.githubusercontent.com/60916587/196917299-5a9b598c-08d0-4dc8-b363-a297066ff518.png)

**Comment by SteveJunGao** [comment]
Hi @anna-debug,

From the error log, it seems you need to put the correct `data_camera_mode` in this [line](https://github.com/nv-tlabs/GET3D/blob/master/training/discriminator_architecture.py#L552), It's also required [here](https://github.com/nv-tlabs/GET3D/blob/master/training/discriminator_architecture.py#L610), make sure you're using a correct `data_camera_mode`

**Comment by anna-debug** [comment]
Ahh, yes, it seems I had missed out those lines, thank you! 
But after putting everything in order there I get new a new error. It seems that the camera angle is not found or is read off incorrectly, however the camera files are found and there isn't a problem in that. 
![no_cam](https://user-images.githubusercontent.com/60916587/197339780-62691bc4-da45-4d57-9362-cdddd28a1da3.png)

**Comment by anna-debug** [comment]
Ahh, yes, it seems I had missed out those lines, thank you!
But after putting everything in order there I get a new error. It seems that some camera angles aren't found or are read off incorrectly, however some of them are. 

![caaaam](https://user-images.githubusercontent.com/60916587/197340418-04baf902-2eb4-447e-9f80-22bc8a7ce447.png)

**Comment by anna-debug** [comment]
Thank you, I got it to work!

**Comment by lenashamseldin** [comment]
@anna-debug Hey Anna, could you please share how you got training to work? What parameters did you change to train on my own dataset? Also do I need to provide paths to images as well as obj files? Would appreciate your help:)
