### ISSUE TITLE
Final step of environment setup / WGET

### ISSUE THREAD

**Issue by AntimodularResearch** [nv-tlabs/GET3D#5]
First of all, congratulations to the team for such groundbreaking work! I'm not a programmer but 20+ years in CGI have forced me to try and understand code. I'm on Win10, using Anaconda, my environment is pretty much configured, except that on the very last step according to the readme, I get an error when running this wget command:

wget https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl

The error states the identity of the server could not be confirmed and suggests using a flag to bypass authentication but ngc rejects such a connection. I've gone through the NGC documentation and in the NGC library we can generate wget or curl commands to pull stuff but they are identical to what the readme suggests. I've created an NGC account and gone through the setup, which generates a config file, but haven't been able to use that when calling wget. I know this is not even related to the project but for other up-and-coming W10 users this might be a point where they get stuck. Any pointers?

Thanks in advance,
L

**Comment by SteveJunGao** [comment]
Thanks for trying it on Windows!

According to this [issue](https://github.com/NVlabs/stylegan3/issues/20) from stylegan3 github repo, can you try to open this [link](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan3/files) in your browser? Then under the bullet `File Browser` you can go to `metrics` and download the `inception-2015-12-05.pkl` one

**Comment by AntimodularResearch** [comment]
Yes, I managed to download the file from the NGC catalog, but should it be placed on the project's root or someplace else?

Cheers,
L

**Comment by SteveJunGao** [comment]
Awesome!

The `inception-2015-12-05.pkl` should be placed under the folder `cache`.

**Comment by bitRAKE** [comment]
New windows has ```curl``` and the following command is effective for me:
```cmd
curl -LO "https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl"
```

**Comment by SteveJunGao** [comment]
Thank you for providing the correct command for the Windows system, @bitRAKE!!

I close this issue for now, and if the problem occurs again, feel free to reopen it.

**Comment by AntimodularResearch** [comment]
Thanks to bitRAKE for providing the curl command for W10!
