### ISSUE TITLE
I have a bug that is fatal error: EGL/egl.h: No such file or directory. 

### ISSUE THREAD

**Issue by BIG-PIE-MILK-COW** [nv-tlabs/GET3D#50]
I met this bug when I try training. Here are the details.

[3/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/TH -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o
FAILED: glutil.o
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/TH -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /SSD_DISK/users/qianjiachen/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o
In file included from /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp:14:
/SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
36 | #include <EGL/egl.h>
| ^~~~~~~~~~~
compilation terminated.

**Comment by SteveJunGao** [comment]
Hi @BIG-PIE-MILK-COW,

Have you installed OpenGL on your machine? this error indicates the compiler could not find the OpenGL files, you can follow this [docker file](https://github.com/nv-tlabs/GET3D/blob/master/docker/Dockerfile#L14) to install the required packages. 

Another option is to replace the OpenGL render in Nvdiffrast with Cuda render by changing [this line](https://github.com/nv-tlabs/GET3D/blob/master/uni_rep/render/neural_render.py#L59) from `self.ctx = dr.RasterizeGLContext(device=self.device)` to `self.ctx = dr.RasterizeCudaContext(device=self.device)`.  This will change from OpenGL to Cuda and won't require installing OpenGL.

**Comment by BIG-PIE-MILK-COW** [comment]
> Hi @BIG-PIE-MILK-COW,
> 
> Have you installed OpenGL on your machine? this error indicates the compiler could not find the OpenGL files, you can follow this [docker file](https://github.com/nv-tlabs/GET3D/blob/master/docker/Dockerfile#L14) to install the required packages.
> 
> Another option is to replace the OpenGL render in Nvdiffrast with Cuda render by changing [this line](https://github.com/nv-tlabs/GET3D/blob/master/uni_rep/render/neural_render.py#L59) from `self.ctx = dr.RasterizeGLContext(device=self.device)` to `self.ctx = dr.RasterizeCudaContext(device=self.device)`. This will change from OpenGL to Cuda and won't require installing OpenGL.

Thank you for your reply, I haven't install OpenGL as I use a remote server to train and I don't have the permission to do apt get, so I try your second suggestion and have resolved it, thank you again.

**Comment by SteveJunGao** [comment]
Awesome! Close this issue as resolved
