### ISSUE TITLE
The camera intrinsic of the rendered data

### ISSUE THREAD

**Issue by plusmultiply** [nv-tlabs/GET3D#53]
Hi, thanks for your great work.
I am trying to find the camera intrinsic from the rendering scripts but I did not find anything related to it.
Could you please give me some hint about how to determine the intrinsic of the camera in your rendering scripts?

**Comment by SteveJunGao** [comment]
Hi @plusmultiply,

The camera intrinsic is defined through these [two lines](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py#L206-L207)

You can also find the intrinsic matrix (in Opengl format) [here](https://github.com/nv-tlabs/GET3D/blob/master/training/networks_get3d.py#L67-L69) this can give you the fovy angle and focal length of the camera

**Comment by plusmultiply** [comment]
Thank you very much. My question is resolved.
