### ISSUE TITLE
Hi Are you going to add zero-shot single image to 3D model , or text to 3d model?

### ISSUE THREAD

**Issue by Hamad-exarta** [nv-tlabs/GET3D#54]
Are you going to add zero-shot single image to 3D model , or text to 3d model?

**Comment by Hamad-exarta** [comment]
Are you going to add zero-shot single image to 3D model , or text to 3d model?

**Comment by SteveJunGao** [comment]
Hi @Hamad-exarta,

Our model doesn't support a zero-shot single image to 3D model right now (as also mentioned in this issue #48). 

Regarding text to 3d models, our implementation is based on this [codebase](https://github.com/rinongal/StyleGAN-nada), you can take a look at it and plug it with our model.

**Comment by SteveJunGao** [comment]
Close this issue as no update received
