### ISSUE TITLE
SDF regularization loss

### ISSUE THREAD

**Issue by anchit** [nv-tlabs/GET3D#56]
https://github.com/nv-tlabs/GET3D/blob/18c35f12c9e47124930d4e036d986eebcc543bac/uni_rep/rep_3d/dmtet.py#L371

The paper mentions using this loss. In the code i see this function is not called anywhere. Where is this supposed to fit in?

Thanks!

**Comment by SteveJunGao** [comment]
Hi @anchit,

We used the regularization in this [line](https://github.com/nv-tlabs/GET3D/blob/master/training/loss.py#L134), it's calling a function inside `training/loss.py` and the one you linked is not used in the code, sorry for the confusion!

**Comment by anchit** [comment]
Thanks! i got confused with the various different sdf regularization functions
