### ISSUE TITLE
How to set gamma to generate objects of the bowl category?

### ISSUE THREAD

**Issue by FreeManKim1** [nv-tlabs/GET3D#58]
Thanks for sharing very wonderful work to generate synthetic data.

Now I recognize that I should set gamma according to the complexity of dataset from the issue No.15(https://github.com/nv-tlabs/GET3D/issues/15).

But could you recommend roughly "gamma" value for the "bowl" category data of ShapeNet v1 dataset?

Sample images of "bowl" category look like below.

Thanks in advance.

![reals](https://user-images.githubusercontent.com/117709039/200484179-cc56f259-ef83-4880-9a11-d6af7e6e1b51.png)

**Comment by SteveJunGao** [comment]
Hi @FreeManKim1,

It's hard to guess one gamma value for one particular category. You can try some values like `10`, `20` or `40`, and pick the best one. 

generally speaking, if the object geometry is complex (e.g. chairs are much more complex than cars), we need a higher gamma value, but if the geometry is simple (e.g. cars, human characters), we can use a lower gamma value

**Comment by FreeManKim1** [comment]
@SteveJunGao 

Thanks a lot for your insightful advice~!

I'll try some gamma values such as 10, 20, or 40.
