### ISSUE TITLE
Issue on rendering Shapenet Dataset

### ISSUE THREAD

**Issue by AmanKishore** [nv-tlabs/GET3D#6]
When running:
`python render_all.py --save_folder dataset/ --dataset_folder ShapeNetCore.v1/ --blender_root <path-to-blender>`

Getting the following error:
```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
```

**Comment by SteveJunGao** [comment]
Hi @AmanKishore,

the script would still work with this error (render the images and save cameras). I also have seen the same output before

**Comment by AmanKishore** [comment]
Cool, I was about to comment that it doesn't seem like an issue and can be ignored!
Thank you for the quick response!

**Comment by AmanKishore** [comment]
@SteveJunGao Quick follow up, how long is the render_all script supposed to take? And is it dependant on GPU memory?

**Comment by SteveJunGao** [comment]
It depends on the type of GPU card you're using. Typically, it can run 2-3 days

**Comment by AmanKishore** [comment]
Whoa that's extensive, any ideas on how to parallelize that across 8 GPUs?

**Comment by SteveJunGao** [comment]
You can split the whole shapenet objects into 8 different subsets, then use each GPU to render each subset. E.g GPU0 render 0-1000, GPU1 render 1000-2000, etc.

**Comment by AmanKishore** [comment]
Good suggestion!
