### ISSUE TITLE
Transformation matrix for rendering

### ISSUE THREAD

**Issue by XinYu-Andy** [nv-tlabs/GET3D#60]
Hi!
Thanks for your great work!
I am trying to use [this function](https://github.com/nv-tlabs/GET3D/blob/6fda9cd15ab78e88db3ba00766df489a3ce88b41/uni_rep/render/neural_render.py#L38) in your code to render a depth given a view. 
I am wondering if the parameter "camera_mv_bx4x4" is consistent with the transformation matrix (defined [here](https://github.com/nv-tlabs/GET3D/blob/6fda9cd15ab78e88db3ba00766df489a3ce88b41/render_shapenet_data/render_shapenet.py#L275)) of the rendered texture image?
Because I find it will produce nothing in this way.

**Comment by StevenLiuWen** [comment]
I have the same concerns on the camera transformation matrix.
