### ISSUE TITLE
ninja: build stopped

### ISSUE THREAD

**Issue by Chinees-zhang** [nv-tlabs/GET3D#61]
I do have some error like this, would you please to give some ideas please.
---------------------------------------------------------------------------------------------
"compilation terminated.
ninja: build stopped: subcommand failed."
--------------------------------------------------------------------------------------------
<img width="919" alt="20221117170918" src="https://user-images.githubusercontent.com/95740471/202407674-91244ae1-e765-4b70-8167-163ad91f2ef4.png">
<img width="919" alt="20221117170919" src="https://user-images.githubusercontent.com/95740471/202407681-4aa49109-5d22-4229-9de0-bf6ec5e22742.png">

**Comment by Chinees-zhang** [comment]
Refer to this [issue](https://github.com/nv-tlabs/GET3D/issues/50#issuecomment-1288166686), my question is resolved.

Thank you very much. @SteveJunGao

**Comment by Chinees-zhang** [comment]
Refer to this https://github.com/nv-tlabs/GET3D/issues/50#issuecomment-1288166686, my question is resolved.

Thank you very much. @SteveJunGao
<img width="697" alt="issue_close" src="https://user-images.githubusercontent.com/95740471/202669108-7e23fa2d-f749-4f89-8ae2-a0c74a01f18b.png">

**Comment by Chinees-zhang** [comment]
Refer to this https://github.com/nv-tlabs/GET3D/issues/50#issuecomment-1288166686, my question has been resolved.

Thank you very much. @SteveJunGao
<img width="697" alt="issue_close" src="https://user-images.githubusercontent.com/95740471/202669364-51e67b70-a097-416f-8c6c-a10f6b4c4391.png">

**Comment by SteveJunGao** [comment]
Thanks for trying our code! 

Glad to see you have fixed the issue!

**Comment by Chinees-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在正忙，无法亲自回复您的邮件。我将在抽时间，尽快给您回复。
