### ISSUE TITLE
How to train the model based on the last training data

### ISSUE THREAD

**Issue by wuyiangel** [nv-tlabs/GET3D#63]
Hello, I would like to ask how get3d training the model based on the last training data. 
For example:

First training: 
python train_3d.py --outdir=PATH_TO_LOG --data=PATH_TO_RENDER_IMG --camera_path PATH_TO_RENDER_CAMERA --gpus=8 --batch=32 --gamma=40 --data_camera_mode shapenet_car --dmtet_scale 1.0 --use_shapenet_split 1 --one_3d_generator 1 --fp32 0

Second training (base on the first training data "network-snapshot-000200.pt"): 
python train_3d.py **--resume_pretrain network-snapshot-000200.pt** --outdir=PATH_TO_LOG --data=PATH_TO_RENDER_IMG --camera_path PATH_TO_RENDER_CAMERA --gpus=8 --batch=32 --gamma=40 --data_camera_mode shapenet_car --dmtet_scale 1.0 --use_shapenet_split 1 --one_3d_generator 1 --fp32 0

I would like to know whether the parameters "--resume_pretrain network-snapshot-000200.pt" I used for the second training is correct. Thinks.

**Comment by SteveJunGao** [comment]
Yes, to resume training from a pretrained network, you only need to pass the argument `--resume_pretrain PATH_TO_YOUR_CKPT` and it should work. 

Note that, in our codebase, we only load the weight for the network and we do NOT load the statistics for the optimizers.

**Comment by SteveJunGao** [comment]
Close this issue as no update received
