### ISSUE TITLE
training on different classes from shapenet

### ISSUE THREAD

**Issue by mujtaba-hike** [nv-tlabs/GET3D#64]
Hi, is it possible to train on other classes from shapenet? what is PATH_TO_RENDER_CAMERA

**Comment by SteveJunGao** [comment]
Hi, @mujtaba-hike ,

Yes, it is possible to train on other classes from shapenet.

The `PATH_TO_RENDER_CAMERA` is the path to the camera parameters for each rendered images, you can check this [script](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py#L237-L238) to get more details about the camera

**Comment by mujtaba-hike** [comment]
i am getting this error:
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Loading training set...
==> use shapenet dataset
==> use ts shapenet motorbike split train
==> use shapenet folder number 231
==> use image path: /nfs_storage/fs-mnt6/mujtaba/3D_vision/GenAI/shapenet/get3d_proc_data_cmc/img/, num images: 0
Traceback (most recent call last):
  File "train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/nfs_storage/fs-mnt6/mujtaba/anaconda3/envs/baes/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nfs_storage/fs-mnt6/mujtaba/anaconda3/envs/baes/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nfs_storage/fs-mnt6/mujtaba/anaconda3/envs/baes/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs_storage/fs-mnt6/mujtaba/anaconda3/envs/baes/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "/nfs_storage/fs-mnt6/mujtaba/3D_vision/GenAI/GET3D/training/training_loop_3d.py", line 135, in training_loop
    dataset=training_set, rank=rank, num_replicas=num_gpus, seed=random_seed)
  File "/nfs_storage/fs-mnt6/mujtaba/3D_vision/GenAI/GET3D/torch_utils/misc.py", line 120, in __init__
    assert len(dataset) > 0
AssertionError


Although I have data in the folder generated by using render_shapenet_data:

ls /nfs_storage/fs-mnt6/mujtaba/3D_vision/GenAI/shapenet/get3d_proc_data_cmc/img/
103e3c517cd759657395d58407f193ba  66fb059b0102f4275a03ed6c9088ec08  b1bb49d472fa7a39e0dbf31b32c641d1
104d1e5422e79ff667691228a451173a  67bff6cc82b6565dfaa866ab8ff6f59   b1f2ea1859ae2aabe4d4c489303b7b1c
115a5200ff80b5d0b37378f3c85478b4  6819949f5625ca12d0f568c31c1cd62a  b3582e7abddb916c3722d6e4d79b71be
11b1e520db0bf1a1d5dde04c96fd8146  68e8c73ec51aeaaeab548456bc75847f  b4112da294c1febf65c8f8f77b16f337
12f06f32ede64d613ff4d2f5a7608a24  6921ac96d7bedf7bd5dde04c96fd8146  b649be9c09e2b332429f1c522640e6f0
12ffd15dabd7e3b596b84415a3f1393b  6a05091b7b1bae0352fa4ad29a1236d7  b767982d38b5171e429f1c522640e6f0
13a245da7b0567509c6d15186da929c5  6a9db96b3ed76f956dc3fd80522499a5  b91424e8cef60e3e1bcfe9129a6aea3a
152de80e31b016d4ced49279fbb1dcc7  6ad8d3973ccf496370a48b7db120f9fc  b91b7ff8ff1b59c6a88e8cb97b773125
1650afa5bf6c8335b37378f3c85478b4  6b6cf38ed305dc11ab13c10f92a32fc1  ba0f7f4b5756e8795ae200efe59d16d0
170cfc531a4fd09fe6905ba5363784c3  6b93d5f2e88326f91f80189578e6ea85  ba9a5f13dcd8312f543a79ca976efea2
177c8a8394f5a78772408d74edbb952e  6bf1f988493dc23752ee90e577613070  bae59e64a50d3aa2f68f798d07e007b6
179998dd1743facfd5dde04c96fd8146  6ce7a58297a6fa5c8249f134aca4c817  bb1c9e1346c5262bedb66d5d04c0da43
18f5c9d827522c859cfdf97abe35029d  6d4ee0be5746095d7c088bd2a4124c69  bc1a3e925e6da7a97bf525c97f9f490c
1a2d2208f73d0531cec33e62192b66e5  6e1397773a4d15db429f1c522640e6f0  bcabe20e46e5126ed5dde04c96fd8146
1a48f3b3c0ab0fdeba8e0a95fbfb7c9   6e37615194e808d3b37378f3c85478b4  bcbcfdad5e0e1d9ba88e8cb97b773125
1d8fb258aac4175a5834749a5ef37100  6ea0a49bd27fa58b2279b76b11a9a16c  bf7794ea4ceb978bafc70af22a99299d
1e664c94e932ece9883158c0007ed9ba  6ebb8ff387bc2510c17fa08d127e11f7  c1acd4ce749a46a6dc2693ab94b1f3be
22ae98e613bb8e188249f134aca4c817  707dfe4769f3e3c5ebe67d9b32c3ddf8  c2d942244bae1557b37378f3c85478b4
242d8c07fabbdabc78fe949fc1419876  70d9cc5115bfedeeab548456bc75847f  c2f26a9646369c6d373c34785838ee4
24359f14ac176b13d270caeadc60b9bb  733b75e867591d0fb37378f3c85478b4  c38b3d9be97383c2ebe67d9b32c3ddf8
24e12e9dfab0892e468bac13e007a6e9  73fd19410ce60b83d5dde04c96fd8146  c43742bc6e7dd467e8e23c8de25a6ff4
25ae9e6628ed05d81e32f79edfad8027  744ab910c5fa999fa036c9ce469c98ce  c4e0be3db8960e7799c206f2618a97af
2610c94869f2456c3630e1f3568e4cec  74a3df7e06713f4a48272812609617e2  c52be51c1aa7cc9752fa4ad29a1236d7
269bfe1b994ac28617798af67b81f2f   75f2dbb8204c01a4e1720743367d35c4  c62066c1ff268bcb9624f6cadda65407
27733dbe070efcd8c9a9842c993649ff  766002ed9dc8556d390c1a9993716e73  c6fbae9bbff2829db3a2525d53af0903
295de7567ed18e692692003428d9fde9  77e00aae33f3ecb4f5724931a8c2eb52  c7c8d9406c1a93ab52a0573c504629a6
2c6e2d1e743b93b67f44d6925c8a069   780767b19b3201fc80ac3c28ee20beb9  c8a99ee61a2003308b543692e5ab59d9
2d50553277d64ebda513de4eb79b310d  788d59c1aa057d8452ee90e577613070  c8d62fbab07d49a7e398c671c3b93e96
2d655fc4ecb2df2a747c19778aa6cc0   7b4eb8cbc470d0d6d5dde04c96fd8146  c90d74aa63043e5ad0f568c31c1cd62a
2f32164c5a422fe8b44d82a74ebc14c0  7b58dca40a1e09dd393c2e9c64ac953   c9c41d106fc36402b0f9875a6c9bf605
2fa098eefef49c8c85b48ea6a7114159  7b6d89ff70831e71594057aa2102e240  c9e2437df080309baab0751e11299b9f
2ff252507b18ce60cd4bec905df51d1d  7c34fdccf25e4113d5dde04c96fd8146  cbf639979de64e14739936b7765e22ae
30157c4a6c09f884c97a3fcdcfe70d5   7c4fc3a05d5fc8b1d0f568c31c1cd62a  cc213702fcec23677395d58407f193ba
30968c53e0d37b6448c90b3a2fec4b8   7c989bfae27a958b615e82f53965c4cc  ccefa6fea8b7a57281eb6e0cf97c3b0b
30f5eec1a7fbb5884fcfb655743e93d8  7d75e8200565ffa7b37378f3c85478b4  cdd1e5890e5a766a65397d05162306e
3156fd3e3101da329b0e27507dc1a100  7fcee59a33976221a88e8cb97b773125  ce46af9eb70d91e2b37378f3c85478b4
31a96fc694f0e58cd5dde04c96fd8146  80011e85cd42668ad373c34785838ee4  cfb2cd4ed1ee0de56dacd34e70282fc3
329e47988e39df1b8c1912cd8631ab82  8020984fc6e83ac1331b5e6778e27aa   d08e47404f0fa3f6a05d44ba0445fced
3339fcde0648dadd11d830afc8c91af   8032295bd3851d75468bac13e007a6e9  d165adb88d2e569552ee90e577613070
3388b8d2486d366ab19ce2dec0d1925   803f90199731098552ee90e577613070  d2f6dec6d70b111fda8b038dea29f4da
33aa1eadcd21734148272812609617e2  80e717f07645a4a0b37378f3c85478b4  d3e1ee410274fe4036abd307db1ff816
33b1973524b81c4ecafb6b9dbe847b85  8134a965cc0b134bb37378f3c85478b4  d54e0f22d4604d741f24b86004bccc4d
346e30470cfbabdd7395d58407f193ba  818a641ccb945f6ecd03ad51b6badc3d  d644ca9d10aed7cdcd4bec905df51d1d
365c1f92a54c8cb52a45a87054fa7272  81e1a6c5a4de9f8f7a1f4451e23d8e4d  d6bef9011ee021c677b7d0d4764c121d
3837c8ef573c2a7b360cf6eb12fae4    828210e9d0a307c0a9a5251e8f29bd8c  d82165e9ab3cbde7eba25bbcd3786140
3a247c8b82bd675c1fbdb352261d023   82c8d89f0d15429a17bf584c2afe53e1  d8ee11cff3188479e7299bc85dbe3a65
3a94134ec9698b74ec5901a85efd6b67  832c4a316c419228b37378f3c85478b4  d91a81a1d57ce78a739936b7765e22ae
3d37db1d974499287395d58407f193ba  837330924dba611df6572e2c76e2d78e  d929925b54d82db139e5b34b546caf02
3de5068dfcbc766d3b44aa8d94a815c0  83d3483c6c9edc39949b12cf3977a48b  d94a099c6a1ca8def4cddc55888e6926
3ef6b2e0a896e4ce54d08b5b71c0b603  8521276f8a6df852c83b248a54afdeb1  d9a4e331d1ade5277395d58407f193ba
3fd1bff496b369f71765540024eb9fef  867e3e502de5cc0dd5dde04c96fd8146  d9ae53fbacf92182b37378f3c85478b4
40b7a63fd9ede0cf48272812609617e2  86a247b7f3be38957395d58407f193ba  db5b6c2f64fefe5b448c90b3a2fec4b8
40d84e407c46e8d8b31e74d456742c7   86b6dc954e1ca8e948272812609617e2  dd38890e85c6dd91138452c33de4a3d
41cc9674e700c3fdb37378f3c85478b4  86b8e4e5ed18fe082a45a87054fa7272  de1f30fbebaa2cd675e2c647bf7937f3
42857ece33bd9119617798af67b81f2f  88950eedce83a11ad4fea43a014cf734  de4d518333b82995d5dde04c96fd8146
42b5ea257418825b5c11b538bde9e3f1  896f688e07909b9b893e67220bf9be7   e033e7dc322bf8a133735c05ad7be6dd
45009f5fa4cb295e52ee90e577613070  89aa8433ae3b9a197395d58407f193ba  e036a72a92033782b9ba8289eb4d47d
450aa58cb4bcd8a34d8ad024e30db0d   89c948e75d1c5cde27e168bcc3c092cb  e1382731f6fedaefd6207a00f6cde01c
4548d86cf7f1c11ad373c34785838ee4  8a5175f5b9be6f34e91fe7b067344e07  e1dbe3832c41e45a8f23c5d2712dcf1e
455485399ab75f93429f1c522640e6f0  8a9586b8eff9f3a6932abeb6e2fd4072  e24b42fe6296c613be23697565633b75
45b69ab448b01056267aabe46d1527a0  8b2e7ae8b0f0d451d97964d17de80d2c  e30b8ae3e945d7f5a40fa6b4bae5e67d
464a86f04b0f6e452a643a53ea2e7c56  8bf620bd023c602b74f7bf9c15b075d9  e38201d0af98e566ba85a673915bd3d
46afe9d5d8a45a17a26d3c6c2e980dd5  8cc21006e2d9f38fb4f2746c8140d6d6  e3de3a51ebcc57f2635b931be375e37
46e38cf88b07de0ee2b85785c47c5d52  8cf5bd117e04da6d6a3456c0ab5674a9  e54d1fb6aaabcaf8d5dde04c96fd8146
47054c1839830834a88e8cb97b773125  8da04b6c03068e6ae21ad659cc6e09ee  e553d75a3635229b429f1c522640e6f0
481f7a57a12517e0fe1b9fad6c90c7bf  8e956bae37beff87c2743f037f439af3  e55e06e7a84f49e2b37378f3c85478b4
48233d99d0bd59e5d8a587623571014e  8ed4bdaf0c8b88ea8b31e74d456742c7  e5747516a94cc4c9e8d78fb938bac492
48372a904ec9cda048272812609617e2  8f032c42d53b5c79aca88bdc785b0d2f  e59b0be8520e4a899cbc1c09129e1507
485a6b42bc4f7e59d373c34785838ee4  8fd0238d882c6f45e3e8453287c65951  e5a9a7b8c947aaa1949b12cf3977a48b
4878886fb154d54366c6576de41cd6b9  90a521e0def2631fd5dde04c96fd8146  e63a6a3a0c9765433d6587690e56f61
48bd19f7d6a20c5c52ee90e577613070  90c209ff795be387afe1d4530f4c6e24  e65c320aa245854e39e5b34b546caf02
49b7ec863c4599aabd1734e75169b9e0  90dd1c4d894653322cbca070ad1b4ac0  e792c49e0e4b2872d83cd5d7c4553c91
49edb54e97458de8d373c34785838ee4  9154fc120f53eaa8d42c4cee3f9bac47  e7c8dd1efb78b8baba85a673915bd3d
4a2f0b20ef680347395d58407f193ba   923ce819405ae29230c72ee872e188e1  e86e4d0b530743e129c87d1be93099f7
4df789715eea8fa552ee90e577613070  9324341a957733ff52ee90e577613070  e9c34796e3c9e46939e8ef80333dae6
4f30742005b7c20e883158c0007ed9ba  9453199691f58147429f1c522640e6f0  ea01df8a5deb6b278e5369269261b398
4fd8e8522a431781924dd6806b28c0a2  94a021f2078cab18da3e5772fc0cd087  eb74f2365d6a55c212fa50e85877ced8
5037cad0901fb395b37378f3c85478b4  966cc24ec5fb927b22b51f1a980f45bf  ebd02a4811dbb91b594057aa2102e240
506962955771904b1d471e626c3ad496  973d75ed9c12836f3d033e6cf82ec72c  ed0d6ea5407e542d31ef331a356b2886
5131b742dad94f6175dadc997718614d  97bb8c467f0efadaf2b5d20b1742ee75  edc4c7a08293697db37378f3c85478b4
52e096f02d12b3bfa70f3e863a68c2c2  98ed7f86a65ed6ad4a6b6d001599a1e5  ee0a3213a08a23d27d2d874548544c4e
52e2bc89667a8e35617798af67b81f2f  992fbae5178edcbc4e31d0cb4d7568    eee947c35691b7d12279b76b11a9a16c
53062381d490e3d1e203ed9c6e5dca08  994dd337f39a32202f2c109faf1ee2c9  ef4bc4af2b7ebf42306928a0ea1eb003
532e6f88a9975a27b37378f3c85478b4  9b9794dda0a6532215a11c390f7ca182  ef5e9989d2e00fd0d95f95e5406fe921
53d6f04450a85fe9ca547803ba354ce   9bc8441b3b70b7014a4c9ebcdcc46c40  ef8672840524f3dea5b5a4b3c46e79b8
543ccc442390ac8ad3e27012e0feb9f   9cb038f61be71ed0cca5d7fbf4f17f56  efe1456e80e2a8646350c50e0a456641
54f016b47a5864cd5dde04c96fd8146   9d3b07f4475d501e8249f134aca4c817  f04281f2440a6821aa213948f4ab1d15
559b67efe09f141052fa4ad29a1236d7  9dd4ae1c34af4766b4f2746c8140d6d6  f06b4f382bac9c9a5a6093c81238167a
55caf44a43f2c04d468bac13e007a6e9  9e9300a6e1caec217395d58407f193ba  f0c7043178a8a2fc52ee90e577613070
56f5e30ad65f01561c6c61410fc904b   9f9de88a95b56660b37378f3c85478b4  f145950bc661e61bc4b71cf5644b0ee1
5742426c4c9fa2e4b37378f3c85478b4  9ff5b01d1aec18b2aae529ab4a75c4af  f160284c3ddbc5df573365aa54129c1b
57a7a9e163e8f087fe11eeaa72c8aa36  a0a40a9d5aabd6a7d5dde04c96fd8146  f1693f82a326cb8afe11eeaa72c8aa36
582e995c76ba36a44f5a72a02a218ed6  a1553e0bb7897a7ace0bf41e5f45753d  f1879331710ab83ca7e3c21092c26d09
58705c949dd5d944d9d3572bbd9cf789  a19d4bb8fe4e70b9d97964d17de80d2c  f26c108283f42995a41f6474541ac161
59a2f0fd2b81bb273b6d7f17f2b61d2d  a2af2d47ac7bd232c3b8d605d6b133fb  f4da1640ad370ce2468bac13e007a6e9
59c019516149fe33d5dde04c96fd8146  a2ee365a26f7ec623228b702032404a6  f521fe88cdfe3a291d87d0fbeec0e0ff
5a1e4b1b6dfe231a362d3a933f999b0   a3dfeae5bced3533b37378f3c85478b4  f5510d06aba5b0f683a3e53900c6cbba
5a34a535ced91869354ab1decf4fe605  a52bac9239f4382ea513de4eb79b310d  f5badefe2a054ff7d1cdd91e6d9c7a4c
5a997a42abaf1a0d52ee90e577613070  a54e8fb64e5879161253ed5a61502f52  f736168c42267866eba25bbcd3786140
5bb3597d49c58017b37378f3c85478b4  a70eb1b6321022e260e00ef7af003fee  f8f73c4ee5da94b076ee2dc2a279fa5e
5bd41c7d3e158ac93ff4d2f5a7608a24  a7554de7ada3163fbec38f8cdf3f0f2c  f93a67db59f4a29cb37378f3c85478b4
5be7e00fe279ac927cb7616d82cf9fae  a9399a50fcb25209429f1c522640e6f0  f959ea5503659fd33bd003e0bb7a3ed9
5c0eaef35c2911ac1d7cf2c1f472233b  a94060c97cfa0c6350bbf5cd198b144c  fad668ac64ccea1ab37378f3c85478b4
5de5e9abd5f49ad7468bac13e007a6e9  a9c432d1dc4034762a45a87054fa7272  fb3e72a17d45156eef7c0039cbd1871c
5df0478fd19f0c175af8505fd49bb4ca  a9e2a1de33b99d08b37378f3c85478b4  fb5d82c273bdad39359c7139c3be4ec1
5e43289edf360d01e937abf44800029d  aa619a9f4b2e200495ff232cd38210b4  fbe400bd5e06d541617798af67b81f2f
5e4fe8a57130744dece0b0a75f5fc9f6  aae0037cd1dd489b468bac13e007a6e9  fd53bf3eb05d8ef4312a95c7d4d74309
6046f323c82b280ea75120c0e0c5316   abdfb5b2d82e555e3bd003e0bb7a3ed9  fdb6223c286cb653cc9e7530f9d8e186
61b17f12bec91d057395d58407f193ba  acd49452b452cf2f3ab3dfa44f5fab01  fea42d4f08c271dcd5dde04c96fd8146
6309c20c1ad258efbb297232fe17fe77  aea3c4f2687e97c92942fa3063963cb6  fede9c1de88d225c7395d58407f193ba
655b9dd9425cc3a12a45a87054fa7272  af2648ef08812a0aa747c19778aa6cc0  ff1fb5a9dd255b059036436a751dc6c2
6611e5f5092d1ac1104831d5b063e54b  b179e7e416edc37086b7427eea4d0f22
6683e13507dde030f6435254228a9d64  b1ad4777e9a8ad4e6e90540cf031a0dd

**Comment by SteveJunGao** [comment]
This error sounds like you didn't pass the correct path to the `PATH_TO_RENDER_CAMERA`, can you show me your training cmd?

**Comment by SteveJunGao** [comment]
Close this issue as no update received
