### ISSUE TITLE
Question about shapenet dataset

### ISSUE THREAD

**Issue by XinYu-Andy** [nv-tlabs/GET3D#66]
Hi,
I found that for some mesh models, there exists a  "failed to load image" error when I use blender to render the multi-view images.
I checked the mesh data in ShapeNetCoreV1. and found that , for some models , e.g. chair 1006be65e7bc937e9141f9b58470d646, it actually does not have a texture uv-map while been indicated in the .obj file.
I am wondering if this is a normal problem, or I have missed something?
I want to ensure that I was rendering proper multi-view images. For example, below is one view of the "chair 1006be65e7bc937e9141f9b58470d646" that I rendered:
![004](https://user-images.githubusercontent.com/60741299/205440771-733e7224-bcb9-47e2-b484-3da97917c832.png)

Thank you very much!

**Comment by SteveJunGao** [comment]
Hi @XinYu-Andy,

This is the correct output, the main reason why you see the purple color is that some objects in ShapeNet do not have correct textures, and Blender will choose to paste purple to fill in the texture map if it's corrupted.

**Comment by XinYu-Andy** [comment]
Thanks for your reply!
Jun Gao ***@***.***>于2022年12月6日 周二04:41写道：
