### ISSUE TITLE
Inference Error on Aws Sagemaker

### ISSUE THREAD

**Issue by hamzafar** [nv-tlabs/GET3D#67]
Hi,

I am implementing/reproducing Get3D on aws sage maker. 

I have installed all the [required](https://github.com/nv-tlabs/GET3D#requirements) packages mentioned on the GitHub. And when I am trying to inference by running the code:
`python train_3d.py --outdir=save_inference_results/shapenet_car  --gpus=1 --batch=4 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0 --inference_vis 1 --resume_pretrain MODEL_PATH
`
I am getting following error:
![image](https://user-images.githubusercontent.com/6842017/206776921-d65cb369-388b-4f84-9707-f941b8735452.png)

I have replicated same code on Google Colab and I am able to get the output in save_inference_results folder.

**Comment by SteveJunGao** [comment]
Hi @hamzafar,

This probably related to this [issue](https://github.com/nv-tlabs/GET3D/issues/50#issuecomment-1288166686), can you check it can see whether the proposed method can fix it?
