### ISSUE TITLE
any support for Mac M1?

### ISSUE THREAD

**Issue by metaphysician** [nv-tlabs/GET3D#7]
congrats on an amazing achievement! i'm on a MacStudio M1 Max with 64 GB of shared RAM so i can run it on 16GB. can this be run as is or has anyone actually tried running it on a Mac M1/M2? if not is there any plan for a Google Colab version? also wondering if there's a forum to get info from others trying this out?

**Comment by SteveJunGao** [comment]
Hi @metaphysician,

We developed our model on the Linux system and haven't tried it on Mac M1/M2, as the code requires CUDA enabled Nvidia graphics card, and Mac doesn't have it. You can always run this code with a cloud service provider that has GPU access. 

We do have a plan for a Google Colab to test our model, but we need to first make sure we can go through the license restrictions from our training dataset. If we are able to release it, then I will update this GitHub repo and provide a link for the trial. 

Thanks for your interest in GET3D, and let me know if you have other questions!

**Comment by metaphysician** [comment]
thanks for the reply @SteveJunGao - i did read that earlier this year PyTorch now supports Apple Silicon over here:
https://sebastianraschka.com/blog/2022/pytorch-m1-gpu.html

however, i don't know if other dependencies are required in the code that currently don't support M1/M2. at any rate i'll stay tuned for the Google Colab possibility. cheers!

**Comment by SteveJunGao** [comment]
Thank you!

We do have some custom cuda kernels that may not be able to use M1/M2 chips, e.g. `nvdiffrast`, `grid_sample_gradfix`, `conv2d_gradfix`, extending these cuda kernels to M1/M2 chips is beyond the effort of our project. 

I will try to upload the Google Colab if there are no restrictions on the license.  Stay tuned!

Close the issue for now
