### ISSUE TITLE
Not found camera root

### ISSUE THREAD

**Issue by dheeraj-pant** [nv-tlabs/GET3D#70]
I have used this command to run 
python train_3d.py --outdir=../../dataset/log --data=../../dataset/car_image/img/02958343 --camera_path ../../dataset/car_image/camera/02958343 --gpus=1 --batch=32 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0

Its able to detect total number of images but says not found camera root. Below is the output that i am getting:

Creating output directory...
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Loading training set...
==> use shapenet dataset
==> use shapenet folder number 1398
==> use image path: ../../dataset/car_image/img/02958343, num images: 33512

Num images:  33512
Image shape: [3, 1024, 1024]
Label shape: [0]

Constructing networks...
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
Initializing logs...
Skipping tfevents export: No module named 'tensorboard'
Training for 20000 kimg...

==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
==> not found camera root
Traceback (most recent call last):
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/envs/get3d/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/training_loop_3d.py", line 288, in training_loop
    loss.accumulate_gradients(
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/loss.py", line 104, in accumulate_gradients
    sdf_reg_loss, render_return_value = self.run_G(
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/loss.py", line 75, in run_G
    img, sdf, syn_camera, deformation, v_deformed, mesh_v, mesh_f, mask_pyramid, sdf_reg_loss, render_return_value = self.G.synthesis(
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/networks_get3d.py", line 534, in forward
    tex_hard_mask, sdf_reg_loss, render_return_value = self.generate(ws, camera, **block_kwargs)
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/networks_get3d.py", line 479, in generate
    antilias_mask, hard_mask, return_value = self.render_mesh(mesh_v, mesh_f, cam_mv)
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/training/networks_get3d.py", line 337, in render_mesh
    return_value = self.dmtet_geometry.render_mesh(
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/uni_rep/rep_3d/dmtet.py", line 462, in render_mesh
    tex_pos, mask, hard_mask, rast, v_pos_clip, mask_pyramid, depth = self.renderer.render_mesh(
  File "/home/jupyter/Nerf_Implementation/nvidia_get_3d/GET3D/uni_rep/render/neural_render.py", line 59, in render_mesh
    self.ctx = dr.RasterizeGLContext(device=self.device)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1405, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/conda/envs/get3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/4] c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
FAILED: torch_rasterize_gl.o 
c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
In file included from /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/../common/rasterize_gl.h:16:0,
                 from /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp:12:
/opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp:14:0:
/opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
FAILED: rasterize_gl.o 
c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/envs/get3d/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/get3d/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
In file included from /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.h:16:0,
                 from /opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp:9:
/opt/conda/envs/get3d/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by SteveJunGao** [comment]
Hi @dheeraj-pant ,

Can you show me your training command? It seems you didn't set up the path for the camera correctly from the log.

Regarding the second error (compilation terminated). This is related to this [issue](https://github.com/nv-tlabs/GET3D/issues/61), can you try the fix mentioned in that thread and let me know the updates?

**Comment by dheeraj-pant** [comment]
Hi @SteveJunGao ,

Thanks for reply I am able to resolve the second issues of nvdiffrast but not found camera root I am still getting.

Directory structure:
-dataset
--log

--camera
---1004ac 
----elevation.py
----rotation.py

--img
---1004ac
----img1
.
.
.
----img24
----transform.json


Command using:

python train_3d.py --outdir=../../dataset/log --data=../../dataset/img --camera_path=../../dataset/camera --gpus=1 --batch=32 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0

**Comment by SteveJunGao** [comment]
From this directory structure, 

One assumption in the code when we're loading the cameras is that the original camera should be organized as `camera/synset_idx/model_identifier` thus can you make a subfolder under `camera` and `img`? 


You can also check these [two lines](https://github.com/nv-tlabs/GET3D/blob/master/render_shapenet_data/render_shapenet.py#L227-L228)  when we are creating the cameras and images:
```python
img_follder = os.path.join(os.path.abspath(args.output_folder), 'img', synset_idx, model_identifier)
camera_follder = os.path.join(os.path.abspath(args.output_folder), 'camera', synset_idx, model_identifier)
```

To use the dataset created by our rendering script, you can do this: `--data= os.path.join(os.path.abspath(args.output_folder), 'img', synset_idx)`, and `--camera os.path.join(os.path.abspath(args.output_folder), 'camera')`

**Comment by Tom0072** [comment]
@dheeraj-pant  --data=targetdata_1/img/02958343,you should add actual img folder name in --data parameter.But not add this at camera.

**Comment by SteveJunGao** [comment]
Close this issue as no update received
