### ISSUE TITLE
Is this project goning to release pretrained model of human charactors?

### ISSUE THREAD

**Issue by s11005349** [nv-tlabs/GET3D#77]
In the README.md. I've saw there're some example images showing that this project already have the capabilities of generating 3D model of human charactors.
Are you guys going to release the pretrained model of human charactors?
I'm really interested in those models because there should be a huge demand for human 3D models.

**Comment by SteveJunGao** [comment]
Hi @s11005349,

Thanks for your interest in our work!!! I do have plans to release the checkpoint on human characters, but it needs to go through the license reviewing process before I can release it

**Comment by s11005349** [comment]
Thank you for your reply!

**Comment by TharHtetAungg** [comment]
@SteveJunGao any update ?
