### ISSUE TITLE
Any Colab Setup

### ISSUE THREAD

**Issue by kilik128** [nv-tlabs/GET3D#8]
Hi someone 
i try make one colab 

https://colab.research.google.com/gist/kilik128/9915b90fd8f405f96da36422ecf30f43/get3d.ipynb

look crash at this time 
any idea as welcome
thank's

**Comment by SteveJunGao** [comment]
Thanks for trying our code! 

Could you add the following commands to the end of training commands you're using `--gpus=1 --batch=4` I guess the error is mainly because Colab is only one GPU, but the code is trying to use 8 GPUs (our default)

**Comment by Delta-Ark** [comment]
Could @kilik128 update us when you get it working; thank you so much!

**Comment by lalalune** [comment]
@kilik128 
I have uploaded images for "motorbike" from ShapeNet, and I can generate images for a creative commons-based set if you'd like a datasource for the Colab

**Comment by SteveJunGao** [comment]
Hi, I have provided a Google Colab to test our pretained model [here](https://github.com/nv-tlabs/GET3D/tree/master/pretrained_model)

**Comment by pugztheplug** [comment]
Hi, is it possible to include the pretrained model using the "Houses" datased from Turbosquid?

**Comment by suraj-brahm** [comment]
Hi guys, I am working on an implementation of this to generate Pixar style animal data set that looks like this https://www.omabuarts.com/product/quirky-series-ultimate-pack/

If anyone can help pls ping me on telegram or whatsapp +91-9823670557
