### ISSUE TITLE
After car training finsh,how to custom make my own car

### ISSUE THREAD

**Issue by Tom0072** [nv-tlabs/GET3D#82]
I tried the pretrain module . And it generated some cars with textures.And what should I do to make it work in my workflow.What should I do to make a input to the well train model,photos?I have seen some software like GANverse3D and NERF , they can generate from 2D to 3D.Is it a base technology in GANverse3D?

**Comment by SteveJunGao** [comment]
Hi @Tom0072,

As mentioned in this [issue](https://github.com/nv-tlabs/GET3D/issues/48), we don't support 2D to 3D in this framework, as we're mainly doing unconditional 3D generation (randomly samples one latent code and generate 3D shapes out from it).

two related references that might be helpful for you:

1. [EG3D](https://nvlabs.github.io/eg3d/) has an experiment doing image inversion (from 2D images to 3D models), you can follow it and plugin the same pipeline to our code

2. [PVT](https://arxiv.org/abs/2106.05744) is a well-known method for GAN's inversion, it has many cool ideas to make inversion working better
