### ISSUE TITLE
Please convert it to .exe

### ISSUE THREAD

**Issue by Chimpan-T** [nv-tlabs/GET3D#83]
I'm honestly finding this very hard to run, so can you convert it to .exe?

**Comment by SteveJunGao** [comment]
Hi @Chimpan-T,

Unfortunately, we have only tested the model on Linux, and I'm not familiar with Windows or creating an .exe for it. 

On the other side, we do plan to release it in the NVIDIA Omniverse soon and it should also support Windows in the future! check this blog for more information https://developer.nvidia.com/blog/rapidly-generate-3d-assets-for-virtual-worlds-with-generative-ai/
