### ISSUE TITLE
Put an interface or something simple

### ISSUE THREAD

**Issue by drakgoku** [nv-tlabs/GET3D#84]
There are many things I don't understand.
I have read the ReadMe. The problem is that in an S.O. Windows I don't know how to do it. Surely there is some way.

I have read: https://github.com/nv-tlabs/GET3D/issues/76

Is it so difficult that instead of having to put commands, you create a simple interface that is executable for multiple platforms?

_Can you imagine playing Mario Bross with commands?_

**Comment by Dandelionym** [comment]
They provide a readme in colab, I'm not sure if it is helpful to you. 

Windows platform is not supported very well. My suggestion is that Linux is the first choice to be considered.

**Comment by Tom0072** [comment]
@drakgoku Windows WSL2 support CUDA and docker.You can try to build a wsl2 environment and use the docker install function.

**Comment by SteveJunGao** [comment]
Thanks @Dandelionym  & @Tom0072  for the answers!!

Yes, we only have the model tested on Linux. Deploying this code on Windows is out of the scope of research and would involve a lot of engineering effort. 

Nevertheless, we do plan to release it in the NVIDIA Omniverse soon and it should also support Windows in the future! check this blog for more information https://developer.nvidia.com/blog/rapidly-generate-3d-assets-for-virtual-worlds-with-generative-ai/

**Comment by Dandelionym** [comment]
Thanks @SteveJunGao, hope it will be released soon!
