### ISSUE TITLE
Will the training works with only one RTX 4090 ?

### ISSUE THREAD

**Issue by s11005349** [nv-tlabs/GET3D#85]
Hi, I'm considering build a small work station.
And I want to know if the training part work with one 4090 (with only 24 GB GPU memory) ?
Have any one test it yet?
And also, does anyone had tried to train the model with custom data set?

**Comment by Tom0072** [comment]
I want to use it to gernerate game assets.I tried to train on 3090.It takes a night to render the cars shapenet using BLENDER_EEVEE engine.The GPU MEMORY over 16GB is enough to train.But the speed of training process is the 230sec/kimg , its duration has 20000kimg.So a well pretrain model could take 40 days to train using single 3090.The README says that they used 8 V100 only train for 2 days.So I guess your 4090 will last 20-30 days to get a pretrain.You can try the pretrain folder and download a finished pretrain model(*.pt).And then make a visual inference model with textures to evaluate the quality.It takes 10 minutes.I think it can use as far scenery but not close shot or game assets.It's still to rough.I'm looking forward to your feedback!

**Comment by s11005349** [comment]
@Tom0072 
Thank you so much for your information.
I want to generate some gaming character 3D models too.
A month to get a pretrain is obiously bad.
I would rather try some cloud solution becouse I had not bought the 4090 yet.
