### ISSUE TITLE
Cannot identify the images for training

### ISSUE THREAD

**Issue by Dandelionym** [nv-tlabs/GET3D#87]
Hi, my project folder is:
```
/GET3D
├── train_rander_img
│   └── train
│       └── flowers
│           ├── image1011.jpeg
│           ├── image1012.jpeg
│           ├── image1013.jpeg
            ...
```
However, there is an error:
```
  File "/home/ubuntu/anaconda3/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[path-to-envs]/get3d/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 325, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "[path-to-projret]/GET3D/training/training_loop_3d.py", line 135, in training_loop
    training_set_sampler = misc.InfiniteSampler(
  File "[path-to-projret]/GET3D/torch_utils/misc.py", line 120, in __init__
    assert len(dataset) > 0
AssertionError
```
I set the --data to the path of the flowers folder: `--data=[the-path-to]/flowers`.
 
It cannot identify my images. Is there anything wrong with me?

**Comment by Tom0072** [comment]
@Dandelionym It cannot train without camera data,the program has to know your camera location and angle of your every images just like the shapenet library training.

**Comment by Dandelionym** [comment]
Thank you, @Tom0072! I use a set of images only. I'm confused about the ShapeNet Library's downloading, it seems inaccessible. Do you mean I should have the `transforms.json` file in the camera dir for every image's camera param?

**Comment by Tom0072** [comment]
Yes.I can show you a link:https://link.zhihu.com/?target=https%3A//shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1.zip
But if you want to build models through images,why not use NERF or RealityCapture to build one.

**Comment by Dandelionym** [comment]
> Yes. I can show you a link:https://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1.zip 
> But if you want to build models through images, why not use NERF or RealityCapture to build one?

1. Hi, @Tom0072, thank you for your sharing.
2. Thank you again, using NeRF is a good suggestion and NVIDIA's instant-ngp has great power for that. However, it's a little hard for me to try, especially in the CUDA language.
