### ISSUE TITLE
Release of trained models

### ISSUE THREAD

**Issue by wufeim** [nv-tlabs/GET3D#9]
Hi,

I'm wondering if there are plans to release trained models so we can play with the trained models for inference only.

Thanks.

**Comment by SteveJunGao** [comment]
Hi @wufeim ,

We're working on it! If everything is ok with the licensing restrictions from the dataset our model is trained on, we will then release the pretrained model. Please stay tuned!

**Comment by wufeim** [comment]
Thanks very much!

**Comment by SteveJunGao** [comment]
Hi, We have released the pretrained models [here](https://github.com/nv-tlabs/GET3D/tree/master/pretrained_model)
