### ISSUE TITLE
Till what kimg value should i train this model

### ISSUE THREAD

**Issue by dheeraj-pant** [nv-tlabs/GET3D#90]
Hi,
I am  training Get3d on motorbike shapenet images.

Input data description:
337 motorbike -----> Each with 24 images and camera matrix

Training Command:
python train_3d.py --outdir=PATH_TO_LOG --data=PATH_TO_RENDER_IMG --camera_path PATH_TO_RENDER_CAMERA --gpus=8 --batch=32 --gamma=80 --data_camera_mode shapenet_motorbike  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 0

I check the model pt files for inference and the result is not like your paper not a good geometry one created.

I see by default its training for 20k kimg. Which value should i pick for this  as its not mention in paper .

**Comment by SteveJunGao** [comment]
Hi @dheeraj-pant,

The default is the maximum iterations we used for training, but typically, we choose the checkpoint that achieves the best FID on the validation set.  You can use the tensorboard to visualize the FID on the validation set (we logged it in this [line](https://github.com/nv-tlabs/GET3D/blob/master/training/training_loop_3d.py#L401-L409))

**Comment by samrat213** [comment]
you would start to see results around 100kimgs. if not something went wrong with your changes.

**Comment by SteveJunGao** [comment]
@dheeraj-pant, I'm closing this issue since there has been no update for 3 weeks. Feel free to reopen it if you have any questions!
