### ISSUE TITLE
how many kimg should i train to reproduce the results

### ISSUE THREAD

**Issue by samrat213** [nv-tlabs/GET3D#92]
I am currently training on shapenet chair data, I have trained for 10000 kimgs already. I have not seen any visual result.
how many kimgs should I run it.

**Comment by SteveJunGao** [comment]
Hi @samrat213 ,

All the models output will be saved at the `--outdir`, can you check whether you see this folder? it should contains the visual results (rendered images + generated 3D shapes within `mesh_pred` folder), the checkpoints, the logs and tensorboard output. 

The `--outdir` corresponds to [this line](https://github.com/nv-tlabs/GET3D/blob/master/README.md?plain=1#L101)

**Comment by samrat213** [comment]
I see the rendered images/gifs during training. I am not seeing any substaintial results even after 10000kigms training. 
so I am wondering if the training went wrong or it is just normal at this point.

**Comment by Bathsheba** [comment]
yeah that's not working right, I did some test runs with motorbikes and saw motorbikey things within a few hundred ticks.
