### ISSUE TITLE
How can I use pre-trained models to generate 3d models based on my own images?

### ISSUE THREAD

**Issue by wangniuniu123** [nv-tlabs/GET3D#94]
In the pre-training model test I can get 3d model rendering images and training data. 
But without training my own model, how can I use my own image library to generate the 3d model I want? (This is a basic function of get3d, I think?) I tried to change the '--data' parameter but it shows dataset size=0. 
And the interface to generate interference with 3d models using text is not found, where should I enter text?

I am confused about the process of using get3d to generate 3d models from images, I would be grateful if you could answer this for me.

**Comment by SruthiSudhakar** [comment]
I have the same question. Given multiple (or ideally a single) images of an object from different views, can we use get3d to generate the 3d model?

**Comment by samrat213** [comment]
theortically it should be possible,
you would have to change "class ImageFolderDataset(Dataset):" in dataset.py for your data
it is implemented for shapenet data currently
also if camera parameters are available then it would be easier, I am not sure otherwise.

**Comment by SteveJunGao** [comment]
Yes, as @samrat213 mentioned, theoretically the code should be possible to generate 3d models based on your own images. 

There're some limitations to this although. It's better to have a big dataset of images and we also need the 2D silhouettes for each object in the images, it would also be better to have cameras for each image. 

If you're looking for a single image to 3D shapes, there are some ways to do it, but we do not code it in this repo. As mentioned in this [issue](https://github.com/nv-tlabs/GET3D/issues/48), we're mainly doing unconditional 3D generation (randomly sampling one latent code and generating 3D shapes out from it).

There are two related references that might be helpful for this use case:

[EG3D](https://nvlabs.github.io/eg3d/) has an experiment doing image inversion (from 2D images to 3D models), you can follow it and plug in the same pipeline to our code

[PVT](https://arxiv.org/abs/2106.05744) is a well-known method for GAN's inversion, it has many cool ideas to make inversion work better

**Comment by SteveJunGao** [comment]
I close this issue for now, feel free to reopen it if any additional questions raised

**Comment by DolevAlgam** [comment]
@wangniuniu123 @SruthiSudhakar Did you manage to create something that generates a 3D model based on a single image?

**Comment by wangniuniu123** [comment]
> @wangniuniu123 @SruthiSudhakar Did you manage to create something that generates a 3D model based on a single image?

Yes! We are trying to use NeRF to generate 3d models, but still in process...

**Comment by DolevAlgam** [comment]
> > @wangniuniu123 @SruthiSudhakar Did you manage to create something that generates a 3D model based on a single image?
> 
> Yes! We are trying to use NeRF to generate 3d models, but still in process...

Amazing! please keep us posted :)
