### ISSUE TITLE
Can this work without camera parameters?

### ISSUE THREAD

**Issue by samrat213** [nv-tlabs/GET3D#95]
Can this model work without camera parameters i.e. rotation.npy and elevation.npy?
I have tried to run it without the camera parameters till 1000 ticks on shapenet car but haven't got any car-type object during visualization.

with camera parameters it starts to shows results in 50 ticks only.

**Comment by SteveJunGao** [comment]
Hi,

GET3D can also work without camera parameters. To remove the dependency on the cameras, you can add an option to your training command: `--add_camera_cond 0`. 

The logic behind is: This codebase, by default, will use camera parameters as conditions for the discriminator, and if you remove camera parameters during training, while still using it as a condition, the model will fail to generate reasonable 3D shapes (as I will manually set missing camera parameters to zero, see [this line](https://github.com/nv-tlabs/GET3D/blob/master/training/dataset.py#L294)). the option  `--add_camera_cond 0` will explicitly remove the camera for discriminator.

**Comment by samrat213** [comment]
It worked

**Comment by jingyang2017** [comment]
> Hi,
> 
> GET3D can also work without camera parameters. To remove the dependency on the cameras, you can add an option to your training command: `--add_camera_cond 0`.
> 
> The logic behind is: This codebase, by default, will use camera parameters as conditions for the discriminator, and if you remove camera parameters during training, while still using it as a condition, the model will fail to generate reasonable 3D shapes (as I will manually set missing camera parameters to zero, see [this line](https://github.com/nv-tlabs/GET3D/blob/master/training/dataset.py#L294)). the option `--add_camera_cond 0` will explicitly remove the camera for discriminator.

I had tried training in chair data without camera condition. The generator is still able to generate view consistency images. I am curious how it is achieved?
