### ISSUE TITLE
hello, could you kindly share the code of extracting underlying geometry of 3D-aware synthesis methods like eg3d?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [nv-tlabs/GET3D#97]
As you can see, i am a little bit lazy, since i have found that instant-ngp includes the code to do this, but could you kindly share your code which can seamlessly be applied to Pi-GAN, GRAF and EG3D?

**Comment by SteveJunGao** [comment]
Hi @hitsz-zuoqi,

That's not the main functionality in GET3D. If you're looking for extracting 3D geometry from eg3d,  you can utilize marching cube algorithms, and [Kaolin](https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.conversions.html?highlight=marching#kaolin.ops.conversions.voxelgrids_to_trianglemeshes) implements a PyTorch interface for it.
