### ISSUE TITLE
Can you share the .pkl files on chair and motorbike of EG3D ?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [nv-tlabs/GET3D#98]

**Comment by SteveJunGao** [comment]
Hi @hitsz-zuoqi,

Releasing additional checkpoints that are not related to the main contribution of this paper involves many additional legal approval processes from the company, and I do not have a plan for releasing them, sorry about that! 

It should also be relatively easy to train EG3D using datasets rendered from our scripts and the official implementation of EG3D, I recommend you try that!
